/**
 * Emoji Data - Comprehensive emoji dataset with metadata
 *
 * This module provides the core emoji dataset organized by category,
 * with support for search keywords, aliases, and skin tone modifiers.
 */

import type {
  Emoji,
  EmojiCategory,
  EmojiCategoryInfo,
  SkinToneInfo,
  SkinTone,
} from "./emoji-types";

// Re-export types for convenience
export type {
  Emoji,
  EmojiCategory,
  EmojiCategoryInfo,
  SkinToneInfo,
  SkinTone,
} from "./emoji-types";

// ============================================================================
// Category Definitions
// ============================================================================

export const EMOJI_CATEGORIES: EmojiCategoryInfo[] = [
  { id: "recent", name: "Recently Used", icon: "\u{1F552}", order: 0 },
  { id: "frequent", name: "Frequently Used", icon: "\u{2B50}", order: 1 },
  { id: "smileys", name: "Smileys & Emotion", icon: "\u{1F600}", order: 2 },
  { id: "people", name: "People & Body", icon: "\u{1F44B}", order: 3 },
  { id: "animals", name: "Animals & Nature", icon: "\u{1F431}", order: 4 },
  { id: "food", name: "Food & Drink", icon: "\u{1F355}", order: 5 },
  { id: "travel", name: "Travel & Places", icon: "\u{2708}\u{FE0F}", order: 6 },
  { id: "activities", name: "Activities", icon: "\u{26BD}", order: 7 },
  { id: "objects", name: "Objects", icon: "\u{1F4A1}", order: 8 },
  { id: "symbols", name: "Symbols", icon: "\u{2764}\u{FE0F}", order: 9 },
  { id: "flags", name: "Flags", icon: "\u{1F3F3}\u{FE0F}", order: 10 },
  { id: "custom", name: "Custom", icon: "\u{2B50}", order: 11 },
];

// ============================================================================
// Skin Tone Definitions
// ============================================================================

export const SKIN_TONES: SkinToneInfo[] = [
  { value: "", name: "Default", emoji: "\u{1F44D}" },
  { value: "1F3FB", name: "Light", emoji: "\u{1F44D}\u{1F3FB}" },
  { value: "1F3FC", name: "Medium-Light", emoji: "\u{1F44D}\u{1F3FC}" },
  { value: "1F3FD", name: "Medium", emoji: "\u{1F44D}\u{1F3FD}" },
  { value: "1F3FE", name: "Medium-Dark", emoji: "\u{1F44D}\u{1F3FE}" },
  { value: "1F3FF", name: "Dark", emoji: "\u{1F44D}\u{1F3FF}" },
];

// ============================================================================
// Emoji Dataset
// ============================================================================

/**
 * Comprehensive emoji dataset organized by category
 * Each emoji includes metadata for search and display
 */
export const EMOJI_DATA: Emoji[] = [
  // ==================== Smileys & Emotion ====================
  {
    id: "grinning",
    emoji: "\u{1F600}",
    name: "grinning",
    displayName: "Grinning Face",
    category: "smileys",
    keywords: ["happy", "smile", "joy", "grin"],
    aliases: ["grin"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "smiley",
    emoji: "\u{1F603}",
    name: "smiley",
    displayName: "Grinning Face with Big Eyes",
    category: "smileys",
    keywords: ["happy", "smile", "haha"],
    aliases: [],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "smile",
    emoji: "\u{1F604}",
    name: "smile",
    displayName: "Grinning Face with Smiling Eyes",
    category: "smileys",
    keywords: ["happy", "joy", "pleased"],
    aliases: [],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "grin",
    emoji: "\u{1F601}",
    name: "grin",
    displayName: "Beaming Face with Smiling Eyes",
    category: "smileys",
    keywords: ["happy", "smile", "joy"],
    aliases: [],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "laughing",
    emoji: "\u{1F606}",
    name: "laughing",
    displayName: "Grinning Squinting Face",
    category: "smileys",
    keywords: ["happy", "haha", "lol", "satisfied"],
    aliases: ["satisfied"],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "sweat_smile",
    emoji: "\u{1F605}",
    name: "sweat_smile",
    displayName: "Grinning Face with Sweat",
    category: "smileys",
    keywords: ["hot", "relief", "phew"],
    aliases: [],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "joy",
    emoji: "\u{1F602}",
    name: "joy",
    displayName: "Face with Tears of Joy",
    category: "smileys",
    keywords: ["happy", "tears", "funny", "lol", "lmao", "haha", "crying"],
    aliases: ["lol"],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "rofl",
    emoji: "\u{1F923}",
    name: "rofl",
    displayName: "Rolling on the Floor Laughing",
    category: "smileys",
    keywords: ["laugh", "lol", "haha", "rolling"],
    aliases: ["rolling_on_the_floor_laughing"],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "wink",
    emoji: "\u{1F609}",
    name: "wink",
    displayName: "Winking Face",
    category: "smileys",
    keywords: ["wink", "flirt", "joke"],
    aliases: [],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "blush",
    emoji: "\u{1F60A}",
    name: "blush",
    displayName: "Smiling Face with Smiling Eyes",
    category: "smileys",
    keywords: ["happy", "shy", "pleased"],
    aliases: [],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "innocent",
    emoji: "\u{1F607}",
    name: "innocent",
    displayName: "Smiling Face with Halo",
    category: "smileys",
    keywords: ["angel", "halo", "innocent", "blessed"],
    aliases: ["angel"],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "heart_eyes",
    emoji: "\u{1F60D}",
    name: "heart_eyes",
    displayName: "Smiling Face with Heart-Eyes",
    category: "smileys",
    keywords: ["love", "crush", "adore", "infatuation"],
    aliases: ["love", "in_love"],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "star_struck",
    emoji: "\u{1F929}",
    name: "star_struck",
    displayName: "Star-Struck",
    category: "smileys",
    keywords: ["wow", "excited", "stars", "amazing"],
    aliases: ["starstruck"],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "kissing_heart",
    emoji: "\u{1F618}",
    name: "kissing_heart",
    displayName: "Face Blowing a Kiss",
    category: "smileys",
    keywords: ["love", "kiss", "flirt"],
    aliases: ["kiss"],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "kissing",
    emoji: "\u{1F617}",
    name: "kissing",
    displayName: "Kissing Face",
    category: "smileys",
    keywords: ["kiss", "love"],
    aliases: [],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "yum",
    emoji: "\u{1F60B}",
    name: "yum",
    displayName: "Face Savoring Food",
    category: "smileys",
    keywords: ["delicious", "yummy", "tasty", "hungry"],
    aliases: ["delicious"],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "stuck_out_tongue",
    emoji: "\u{1F61B}",
    name: "stuck_out_tongue",
    displayName: "Face with Tongue",
    category: "smileys",
    keywords: ["playful", "silly", "tongue"],
    aliases: ["tongue"],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "stuck_out_tongue_winking_eye",
    emoji: "\u{1F61C}",
    name: "stuck_out_tongue_winking_eye",
    displayName: "Winking Face with Tongue",
    category: "smileys",
    keywords: ["playful", "silly", "crazy", "joke"],
    aliases: ["crazy"],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "zany",
    emoji: "\u{1F92A}",
    name: "zany",
    displayName: "Zany Face",
    category: "smileys",
    keywords: ["crazy", "silly", "goofy", "wild"],
    aliases: ["zany_face"],
    supportsSkinTone: false,
    order: 19,
  },
  {
    id: "sunglasses",
    emoji: "\u{1F60E}",
    name: "sunglasses",
    displayName: "Smiling Face with Sunglasses",
    category: "smileys",
    keywords: ["cool", "confident", "summer"],
    aliases: ["cool"],
    supportsSkinTone: false,
    order: 20,
  },
  {
    id: "nerd",
    emoji: "\u{1F913}",
    name: "nerd",
    displayName: "Nerd Face",
    category: "smileys",
    keywords: ["geek", "glasses", "smart", "study"],
    aliases: ["nerd_face"],
    supportsSkinTone: false,
    order: 21,
  },
  {
    id: "monocle",
    emoji: "\u{1F9D0}",
    name: "monocle",
    displayName: "Face with Monocle",
    category: "smileys",
    keywords: ["hmm", "thinking", "curious", "fancy"],
    aliases: ["face_with_monocle"],
    supportsSkinTone: false,
    order: 22,
  },
  {
    id: "thinking",
    emoji: "\u{1F914}",
    name: "thinking",
    displayName: "Thinking Face",
    category: "smileys",
    keywords: ["hmm", "ponder", "consider", "wonder"],
    aliases: ["think", "hmm"],
    supportsSkinTone: false,
    order: 23,
  },
  {
    id: "neutral_face",
    emoji: "\u{1F610}",
    name: "neutral_face",
    displayName: "Neutral Face",
    category: "smileys",
    keywords: ["indifferent", "meh", "blank"],
    aliases: ["meh"],
    supportsSkinTone: false,
    order: 24,
  },
  {
    id: "expressionless",
    emoji: "\u{1F611}",
    name: "expressionless",
    displayName: "Expressionless Face",
    category: "smileys",
    keywords: ["blank", "indifferent", "meh"],
    aliases: [],
    supportsSkinTone: false,
    order: 25,
  },
  {
    id: "unamused",
    emoji: "\u{1F612}",
    name: "unamused",
    displayName: "Unamused Face",
    category: "smileys",
    keywords: ["bored", "meh", "annoyed", "skeptical"],
    aliases: [],
    supportsSkinTone: false,
    order: 26,
  },
  {
    id: "roll_eyes",
    emoji: "\u{1F644}",
    name: "roll_eyes",
    displayName: "Face with Rolling Eyes",
    category: "smileys",
    keywords: ["eyeroll", "frustrated", "bored", "whatever"],
    aliases: ["eyeroll"],
    supportsSkinTone: false,
    order: 27,
  },
  {
    id: "grimacing",
    emoji: "\u{1F62C}",
    name: "grimacing",
    displayName: "Grimacing Face",
    category: "smileys",
    keywords: ["awkward", "nervous", "tense"],
    aliases: [],
    supportsSkinTone: false,
    order: 28,
  },
  {
    id: "hushed",
    emoji: "\u{1F62F}",
    name: "hushed",
    displayName: "Hushed Face",
    category: "smileys",
    keywords: ["surprised", "shocked", "speechless"],
    aliases: [],
    supportsSkinTone: false,
    order: 29,
  },
  {
    id: "flushed",
    emoji: "\u{1F633}",
    name: "flushed",
    displayName: "Flushed Face",
    category: "smileys",
    keywords: ["embarrassed", "shy", "shocked"],
    aliases: [],
    supportsSkinTone: false,
    order: 30,
  },
  {
    id: "pleading",
    emoji: "\u{1F97A}",
    name: "pleading",
    displayName: "Pleading Face",
    category: "smileys",
    keywords: ["puppy", "eyes", "please", "cute", "begging"],
    aliases: ["pleading_face"],
    supportsSkinTone: false,
    order: 31,
  },
  {
    id: "relieved",
    emoji: "\u{1F60C}",
    name: "relieved",
    displayName: "Relieved Face",
    category: "smileys",
    keywords: ["relaxed", "calm", "content"],
    aliases: [],
    supportsSkinTone: false,
    order: 32,
  },
  {
    id: "pensive",
    emoji: "\u{1F614}",
    name: "pensive",
    displayName: "Pensive Face",
    category: "smileys",
    keywords: ["sad", "thoughtful", "reflective"],
    aliases: [],
    supportsSkinTone: false,
    order: 33,
  },
  {
    id: "sleepy",
    emoji: "\u{1F62A}",
    name: "sleepy",
    displayName: "Sleepy Face",
    category: "smileys",
    keywords: ["tired", "snot", "bubble"],
    aliases: [],
    supportsSkinTone: false,
    order: 34,
  },
  {
    id: "sleeping",
    emoji: "\u{1F634}",
    name: "sleeping",
    displayName: "Sleeping Face",
    category: "smileys",
    keywords: ["zzz", "tired", "rest"],
    aliases: ["zzz"],
    supportsSkinTone: false,
    order: 35,
  },
  {
    id: "mask",
    emoji: "\u{1F637}",
    name: "mask",
    displayName: "Face with Medical Mask",
    category: "smileys",
    keywords: ["sick", "ill", "covid", "cold"],
    aliases: [],
    supportsSkinTone: false,
    order: 36,
  },
  {
    id: "disappointed",
    emoji: "\u{1F61E}",
    name: "disappointed",
    displayName: "Disappointed Face",
    category: "smileys",
    keywords: ["sad", "upset", "let down"],
    aliases: ["sad"],
    supportsSkinTone: false,
    order: 37,
  },
  {
    id: "worried",
    emoji: "\u{1F61F}",
    name: "worried",
    displayName: "Worried Face",
    category: "smileys",
    keywords: ["anxious", "concerned", "nervous"],
    aliases: [],
    supportsSkinTone: false,
    order: 38,
  },
  {
    id: "angry",
    emoji: "\u{1F620}",
    name: "angry",
    displayName: "Angry Face",
    category: "smileys",
    keywords: ["mad", "annoyed", "frustrated"],
    aliases: ["mad"],
    supportsSkinTone: false,
    order: 39,
  },
  {
    id: "rage",
    emoji: "\u{1F621}",
    name: "rage",
    displayName: "Pouting Face",
    category: "smileys",
    keywords: ["angry", "mad", "hate", "furious"],
    aliases: ["pout"],
    supportsSkinTone: false,
    order: 40,
  },
  {
    id: "cry",
    emoji: "\u{1F622}",
    name: "cry",
    displayName: "Crying Face",
    category: "smileys",
    keywords: ["sad", "tear", "upset"],
    aliases: ["tear"],
    supportsSkinTone: false,
    order: 41,
  },
  {
    id: "sob",
    emoji: "\u{1F62D}",
    name: "sob",
    displayName: "Loudly Crying Face",
    category: "smileys",
    keywords: ["cry", "sad", "upset", "tears"],
    aliases: ["crying"],
    supportsSkinTone: false,
    order: 42,
  },
  {
    id: "scream",
    emoji: "\u{1F631}",
    name: "scream",
    displayName: "Face Screaming in Fear",
    category: "smileys",
    keywords: ["scared", "shocked", "horror", "munch"],
    aliases: ["shocked"],
    supportsSkinTone: false,
    order: 43,
  },
  {
    id: "fearful",
    emoji: "\u{1F628}",
    name: "fearful",
    displayName: "Fearful Face",
    category: "smileys",
    keywords: ["scared", "nervous", "afraid"],
    aliases: ["afraid"],
    supportsSkinTone: false,
    order: 44,
  },
  {
    id: "exploding_head",
    emoji: "\u{1F92F}",
    name: "exploding_head",
    displayName: "Exploding Head",
    category: "smileys",
    keywords: ["shocked", "mind blown", "wow", "amazed"],
    aliases: ["mind_blown"],
    supportsSkinTone: false,
    order: 45,
  },
  {
    id: "partying",
    emoji: "\u{1F973}",
    name: "partying",
    displayName: "Partying Face",
    category: "smileys",
    keywords: ["party", "celebration", "fun", "woohoo"],
    aliases: ["party", "partying_face"],
    supportsSkinTone: false,
    order: 46,
  },
  {
    id: "shush",
    emoji: "\u{1F92B}",
    name: "shush",
    displayName: "Shushing Face",
    category: "smileys",
    keywords: ["quiet", "secret", "shhh"],
    aliases: ["shushing_face"],
    supportsSkinTone: false,
    order: 47,
  },
  {
    id: "skull",
    emoji: "\u{1F480}",
    name: "skull",
    displayName: "Skull",
    category: "smileys",
    keywords: ["dead", "death", "skeleton", "dying"],
    aliases: ["dead", "skeleton"],
    supportsSkinTone: false,
    order: 48,
  },

  // ==================== People & Body ====================
  {
    id: "wave",
    emoji: "\u{1F44B}",
    name: "wave",
    displayName: "Waving Hand",
    category: "people",
    keywords: ["hello", "goodbye", "hi", "bye", "wave"],
    aliases: ["hello", "hi", "bye"],
    supportsSkinTone: true,
    order: 1,
  },
  {
    id: "thumbsup",
    emoji: "\u{1F44D}",
    name: "thumbsup",
    displayName: "Thumbs Up",
    category: "people",
    keywords: ["good", "ok", "yes", "approve", "like"],
    aliases: ["+1", "thumbs_up", "like"],
    supportsSkinTone: true,
    order: 2,
  },
  {
    id: "thumbsdown",
    emoji: "\u{1F44E}",
    name: "thumbsdown",
    displayName: "Thumbs Down",
    category: "people",
    keywords: ["bad", "no", "disapprove", "dislike"],
    aliases: ["-1", "thumbs_down", "dislike"],
    supportsSkinTone: true,
    order: 3,
  },
  {
    id: "ok_hand",
    emoji: "\u{1F44C}",
    name: "ok_hand",
    displayName: "OK Hand",
    category: "people",
    keywords: ["ok", "perfect", "good"],
    aliases: ["ok", "okay"],
    supportsSkinTone: true,
    order: 4,
  },
  {
    id: "clap",
    emoji: "\u{1F44F}",
    name: "clap",
    displayName: "Clapping Hands",
    category: "people",
    keywords: ["applause", "congrats", "bravo", "well done"],
    aliases: ["applause"],
    supportsSkinTone: true,
    order: 5,
  },
  {
    id: "raised_hands",
    emoji: "\u{1F64C}",
    name: "raised_hands",
    displayName: "Raising Hands",
    category: "people",
    keywords: ["hooray", "yay", "celebration", "praise"],
    aliases: ["hooray", "yay"],
    supportsSkinTone: true,
    order: 6,
  },
  {
    id: "pray",
    emoji: "\u{1F64F}",
    name: "pray",
    displayName: "Folded Hands",
    category: "people",
    keywords: ["please", "thank you", "pray", "hope", "namaste"],
    aliases: ["thanks", "please", "namaste", "highfive"],
    supportsSkinTone: true,
    order: 7,
  },
  {
    id: "handshake",
    emoji: "\u{1F91D}",
    name: "handshake",
    displayName: "Handshake",
    category: "people",
    keywords: ["agreement", "deal", "shake"],
    aliases: ["deal"],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "point_up",
    emoji: "\u{261D}\u{FE0F}",
    name: "point_up",
    displayName: "Index Pointing Up",
    category: "people",
    keywords: ["one", "attention", "point"],
    aliases: [],
    supportsSkinTone: true,
    order: 9,
  },
  {
    id: "point_down",
    emoji: "\u{1F447}",
    name: "point_down",
    displayName: "Backhand Index Pointing Down",
    category: "people",
    keywords: ["down", "point", "below"],
    aliases: [],
    supportsSkinTone: true,
    order: 10,
  },
  {
    id: "point_left",
    emoji: "\u{1F448}",
    name: "point_left",
    displayName: "Backhand Index Pointing Left",
    category: "people",
    keywords: ["left", "point", "direction"],
    aliases: [],
    supportsSkinTone: true,
    order: 11,
  },
  {
    id: "point_right",
    emoji: "\u{1F449}",
    name: "point_right",
    displayName: "Backhand Index Pointing Right",
    category: "people",
    keywords: ["right", "point", "direction"],
    aliases: [],
    supportsSkinTone: true,
    order: 12,
  },
  {
    id: "v",
    emoji: "\u{270C}\u{FE0F}",
    name: "v",
    displayName: "Victory Hand",
    category: "people",
    keywords: ["peace", "victory", "two"],
    aliases: ["peace", "victory"],
    supportsSkinTone: true,
    order: 13,
  },
  {
    id: "crossed_fingers",
    emoji: "\u{1F91E}",
    name: "crossed_fingers",
    displayName: "Crossed Fingers",
    category: "people",
    keywords: ["luck", "hope", "wish"],
    aliases: ["fingers_crossed"],
    supportsSkinTone: true,
    order: 14,
  },
  {
    id: "metal",
    emoji: "\u{1F918}",
    name: "metal",
    displayName: "Sign of the Horns",
    category: "people",
    keywords: ["rock", "metal", "music", "cool"],
    aliases: ["rock", "horns"],
    supportsSkinTone: true,
    order: 15,
  },
  {
    id: "call_me",
    emoji: "\u{1F919}",
    name: "call_me",
    displayName: "Call Me Hand",
    category: "people",
    keywords: ["call", "phone", "shaka"],
    aliases: ["call_me_hand", "shaka"],
    supportsSkinTone: true,
    order: 16,
  },
  {
    id: "muscle",
    emoji: "\u{1F4AA}",
    name: "muscle",
    displayName: "Flexed Biceps",
    category: "people",
    keywords: ["strong", "flex", "gym", "workout", "power"],
    aliases: ["strong", "flex"],
    supportsSkinTone: true,
    order: 17,
  },
  {
    id: "fist",
    emoji: "\u{270A}",
    name: "fist",
    displayName: "Raised Fist",
    category: "people",
    keywords: ["punch", "power", "solidarity"],
    aliases: ["punch"],
    supportsSkinTone: true,
    order: 18,
  },
  {
    id: "heart_hands",
    emoji: "\u{1FAF6}",
    name: "heart_hands",
    displayName: "Heart Hands",
    category: "people",
    keywords: ["love", "heart", "affection"],
    aliases: [],
    supportsSkinTone: true,
    order: 19,
  },

  // ==================== Animals & Nature ====================
  {
    id: "dog",
    emoji: "\u{1F436}",
    name: "dog",
    displayName: "Dog Face",
    category: "animals",
    keywords: ["pet", "puppy", "cute", "animal"],
    aliases: ["puppy"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "cat",
    emoji: "\u{1F431}",
    name: "cat",
    displayName: "Cat Face",
    category: "animals",
    keywords: ["pet", "kitty", "cute", "meow"],
    aliases: ["kitty", "meow"],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "fox",
    emoji: "\u{1F98A}",
    name: "fox",
    displayName: "Fox",
    category: "animals",
    keywords: ["cunning", "animal", "cute"],
    aliases: ["fox_face"],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "lion",
    emoji: "\u{1F981}",
    name: "lion",
    displayName: "Lion",
    category: "animals",
    keywords: ["king", "animal", "wild"],
    aliases: ["lion_face"],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "unicorn",
    emoji: "\u{1F984}",
    name: "unicorn",
    displayName: "Unicorn",
    category: "animals",
    keywords: ["magic", "fantasy", "rainbow"],
    aliases: ["unicorn_face"],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "bear",
    emoji: "\u{1F43B}",
    name: "bear",
    displayName: "Bear",
    category: "animals",
    keywords: ["animal", "teddy", "cute"],
    aliases: [],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "panda",
    emoji: "\u{1F43C}",
    name: "panda",
    displayName: "Panda",
    category: "animals",
    keywords: ["animal", "cute", "china"],
    aliases: ["panda_face"],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "penguin",
    emoji: "\u{1F427}",
    name: "penguin",
    displayName: "Penguin",
    category: "animals",
    keywords: ["bird", "cold", "cute", "winter"],
    aliases: [],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "chicken",
    emoji: "\u{1F414}",
    name: "chicken",
    displayName: "Chicken",
    category: "animals",
    keywords: ["bird", "farm", "animal"],
    aliases: [],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "frog",
    emoji: "\u{1F438}",
    name: "frog",
    displayName: "Frog",
    category: "animals",
    keywords: ["toad", "animal", "nature"],
    aliases: ["toad"],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "butterfly",
    emoji: "\u{1F98B}",
    name: "butterfly",
    displayName: "Butterfly",
    category: "animals",
    keywords: ["insect", "beautiful", "nature"],
    aliases: [],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "bee",
    emoji: "\u{1F41D}",
    name: "bee",
    displayName: "Honeybee",
    category: "animals",
    keywords: ["insect", "honey", "busy"],
    aliases: ["honeybee"],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "bug",
    emoji: "\u{1F41B}",
    name: "bug",
    displayName: "Bug",
    category: "animals",
    keywords: ["insect", "caterpillar"],
    aliases: [],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "snake",
    emoji: "\u{1F40D}",
    name: "snake",
    displayName: "Snake",
    category: "animals",
    keywords: ["reptile", "animal"],
    aliases: [],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "turtle",
    emoji: "\u{1F422}",
    name: "turtle",
    displayName: "Turtle",
    category: "animals",
    keywords: ["slow", "animal", "shell"],
    aliases: [],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "octopus",
    emoji: "\u{1F419}",
    name: "octopus",
    displayName: "Octopus",
    category: "animals",
    keywords: ["sea", "ocean", "animal"],
    aliases: [],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "whale",
    emoji: "\u{1F433}",
    name: "whale",
    displayName: "Spouting Whale",
    category: "animals",
    keywords: ["ocean", "sea", "animal"],
    aliases: [],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "dolphin",
    emoji: "\u{1F42C}",
    name: "dolphin",
    displayName: "Dolphin",
    category: "animals",
    keywords: ["ocean", "sea", "smart"],
    aliases: [],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "shark",
    emoji: "\u{1F988}",
    name: "shark",
    displayName: "Shark",
    category: "animals",
    keywords: ["ocean", "predator", "jaws"],
    aliases: [],
    supportsSkinTone: false,
    order: 19,
  },
  {
    id: "rose",
    emoji: "\u{1F339}",
    name: "rose",
    displayName: "Rose",
    category: "animals",
    keywords: ["flower", "love", "romantic"],
    aliases: [],
    supportsSkinTone: false,
    order: 20,
  },
  {
    id: "sunflower",
    emoji: "\u{1F33B}",
    name: "sunflower",
    displayName: "Sunflower",
    category: "animals",
    keywords: ["flower", "nature", "yellow", "sun"],
    aliases: [],
    supportsSkinTone: false,
    order: 21,
  },
  {
    id: "four_leaf_clover",
    emoji: "\u{1F340}",
    name: "four_leaf_clover",
    displayName: "Four Leaf Clover",
    category: "animals",
    keywords: ["luck", "lucky", "irish", "nature"],
    aliases: ["luck", "lucky"],
    supportsSkinTone: false,
    order: 22,
  },
  {
    id: "tree",
    emoji: "\u{1F333}",
    name: "tree",
    displayName: "Deciduous Tree",
    category: "animals",
    keywords: ["nature", "plant", "forest"],
    aliases: [],
    supportsSkinTone: false,
    order: 23,
  },
  {
    id: "cactus",
    emoji: "\u{1F335}",
    name: "cactus",
    displayName: "Cactus",
    category: "animals",
    keywords: ["desert", "plant", "nature"],
    aliases: [],
    supportsSkinTone: false,
    order: 24,
  },

  // ==================== Food & Drink ====================
  {
    id: "apple",
    emoji: "\u{1F34E}",
    name: "apple",
    displayName: "Red Apple",
    category: "food",
    keywords: ["fruit", "red", "healthy"],
    aliases: ["red_apple"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "banana",
    emoji: "\u{1F34C}",
    name: "banana",
    displayName: "Banana",
    category: "food",
    keywords: ["fruit", "yellow", "monkey"],
    aliases: [],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "orange",
    emoji: "\u{1F34A}",
    name: "orange",
    displayName: "Tangerine",
    category: "food",
    keywords: ["fruit", "citrus", "orange"],
    aliases: ["tangerine"],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "lemon",
    emoji: "\u{1F34B}",
    name: "lemon",
    displayName: "Lemon",
    category: "food",
    keywords: ["fruit", "citrus", "sour"],
    aliases: [],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "watermelon",
    emoji: "\u{1F349}",
    name: "watermelon",
    displayName: "Watermelon",
    category: "food",
    keywords: ["fruit", "summer", "sweet"],
    aliases: [],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "grapes",
    emoji: "\u{1F347}",
    name: "grapes",
    displayName: "Grapes",
    category: "food",
    keywords: ["fruit", "wine", "purple"],
    aliases: [],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "strawberry",
    emoji: "\u{1F353}",
    name: "strawberry",
    displayName: "Strawberry",
    category: "food",
    keywords: ["fruit", "berry", "sweet"],
    aliases: [],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "peach",
    emoji: "\u{1F351}",
    name: "peach",
    displayName: "Peach",
    category: "food",
    keywords: ["fruit", "butt", "bottom"],
    aliases: [],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "cherry",
    emoji: "\u{1F352}",
    name: "cherry",
    displayName: "Cherries",
    category: "food",
    keywords: ["fruit", "red", "sweet"],
    aliases: ["cherries"],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "pizza",
    emoji: "\u{1F355}",
    name: "pizza",
    displayName: "Pizza",
    category: "food",
    keywords: ["food", "italian", "slice"],
    aliases: [],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "hamburger",
    emoji: "\u{1F354}",
    name: "hamburger",
    displayName: "Hamburger",
    category: "food",
    keywords: ["food", "burger", "fast food"],
    aliases: ["burger"],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "fries",
    emoji: "\u{1F35F}",
    name: "fries",
    displayName: "French Fries",
    category: "food",
    keywords: ["food", "fast food", "chips"],
    aliases: ["french_fries"],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "hotdog",
    emoji: "\u{1F32D}",
    name: "hotdog",
    displayName: "Hot Dog",
    category: "food",
    keywords: ["food", "sausage"],
    aliases: ["hot_dog"],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "taco",
    emoji: "\u{1F32E}",
    name: "taco",
    displayName: "Taco",
    category: "food",
    keywords: ["food", "mexican"],
    aliases: [],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "burrito",
    emoji: "\u{1F32F}",
    name: "burrito",
    displayName: "Burrito",
    category: "food",
    keywords: ["food", "mexican", "wrap"],
    aliases: [],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "ramen",
    emoji: "\u{1F35C}",
    name: "ramen",
    displayName: "Steaming Bowl",
    category: "food",
    keywords: ["food", "noodles", "japanese", "soup"],
    aliases: ["noodles"],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "sushi",
    emoji: "\u{1F363}",
    name: "sushi",
    displayName: "Sushi",
    category: "food",
    keywords: ["food", "japanese", "fish"],
    aliases: [],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "cake",
    emoji: "\u{1F382}",
    name: "cake",
    displayName: "Birthday Cake",
    category: "food",
    keywords: ["dessert", "birthday", "celebration"],
    aliases: ["birthday"],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "cookie",
    emoji: "\u{1F36A}",
    name: "cookie",
    displayName: "Cookie",
    category: "food",
    keywords: ["dessert", "sweet", "biscuit"],
    aliases: [],
    supportsSkinTone: false,
    order: 19,
  },
  {
    id: "donut",
    emoji: "\u{1F369}",
    name: "donut",
    displayName: "Doughnut",
    category: "food",
    keywords: ["dessert", "sweet", "breakfast"],
    aliases: ["doughnut"],
    supportsSkinTone: false,
    order: 20,
  },
  {
    id: "icecream",
    emoji: "\u{1F368}",
    name: "icecream",
    displayName: "Ice Cream",
    category: "food",
    keywords: ["dessert", "sweet", "cold"],
    aliases: ["ice_cream"],
    supportsSkinTone: false,
    order: 21,
  },
  {
    id: "coffee",
    emoji: "\u{2615}",
    name: "coffee",
    displayName: "Hot Beverage",
    category: "food",
    keywords: ["drink", "caffeine", "tea", "morning"],
    aliases: ["tea", "hot_beverage"],
    supportsSkinTone: false,
    order: 22,
  },
  {
    id: "beer",
    emoji: "\u{1F37A}",
    name: "beer",
    displayName: "Beer Mug",
    category: "food",
    keywords: ["drink", "alcohol", "bar"],
    aliases: [],
    supportsSkinTone: false,
    order: 23,
  },
  {
    id: "wine",
    emoji: "\u{1F377}",
    name: "wine",
    displayName: "Wine Glass",
    category: "food",
    keywords: ["drink", "alcohol", "red"],
    aliases: ["wine_glass"],
    supportsSkinTone: false,
    order: 24,
  },
  {
    id: "champagne",
    emoji: "\u{1F37E}",
    name: "champagne",
    displayName: "Bottle with Popping Cork",
    category: "food",
    keywords: ["drink", "celebration", "party"],
    aliases: ["bottle_with_popping_cork"],
    supportsSkinTone: false,
    order: 25,
  },

  // ==================== Travel & Places ====================
  {
    id: "car",
    emoji: "\u{1F697}",
    name: "car",
    displayName: "Automobile",
    category: "travel",
    keywords: ["vehicle", "drive", "transport"],
    aliases: ["automobile", "red_car"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "taxi",
    emoji: "\u{1F695}",
    name: "taxi",
    displayName: "Taxi",
    category: "travel",
    keywords: ["vehicle", "cab", "transport"],
    aliases: ["cab"],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "bus",
    emoji: "\u{1F68C}",
    name: "bus",
    displayName: "Bus",
    category: "travel",
    keywords: ["vehicle", "transport", "public"],
    aliases: [],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "airplane",
    emoji: "\u{2708}\u{FE0F}",
    name: "airplane",
    displayName: "Airplane",
    category: "travel",
    keywords: ["travel", "flight", "fly"],
    aliases: ["plane", "flight"],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "rocket",
    emoji: "\u{1F680}",
    name: "rocket",
    displayName: "Rocket",
    category: "travel",
    keywords: ["space", "launch", "ship", "fast"],
    aliases: ["ship"],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "helicopter",
    emoji: "\u{1F681}",
    name: "helicopter",
    displayName: "Helicopter",
    category: "travel",
    keywords: ["vehicle", "fly", "transport"],
    aliases: [],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "ship",
    emoji: "\u{1F6A2}",
    name: "ship",
    displayName: "Ship",
    category: "travel",
    keywords: ["boat", "cruise", "ocean"],
    aliases: ["boat", "cruise"],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "bike",
    emoji: "\u{1F6B2}",
    name: "bike",
    displayName: "Bicycle",
    category: "travel",
    keywords: ["vehicle", "cycle", "transport"],
    aliases: ["bicycle"],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "house",
    emoji: "\u{1F3E0}",
    name: "house",
    displayName: "House",
    category: "travel",
    keywords: ["home", "building", "residence"],
    aliases: ["home"],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "office",
    emoji: "\u{1F3E2}",
    name: "office",
    displayName: "Office Building",
    category: "travel",
    keywords: ["work", "building", "business"],
    aliases: ["building"],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "hospital",
    emoji: "\u{1F3E5}",
    name: "hospital",
    displayName: "Hospital",
    category: "travel",
    keywords: ["health", "building", "medical"],
    aliases: [],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "mountain",
    emoji: "\u{26F0}\u{FE0F}",
    name: "mountain",
    displayName: "Mountain",
    category: "travel",
    keywords: ["nature", "outdoor", "hiking"],
    aliases: [],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "beach",
    emoji: "\u{1F3D6}\u{FE0F}",
    name: "beach",
    displayName: "Beach with Umbrella",
    category: "travel",
    keywords: ["summer", "vacation", "sand"],
    aliases: ["beach_umbrella"],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "camping",
    emoji: "\u{1F3D5}\u{FE0F}",
    name: "camping",
    displayName: "Camping",
    category: "travel",
    keywords: ["tent", "outdoor", "nature"],
    aliases: ["tent"],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "sun",
    emoji: "\u{2600}\u{FE0F}",
    name: "sun",
    displayName: "Sun",
    category: "travel",
    keywords: ["weather", "sunny", "bright", "summer"],
    aliases: ["sunny"],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "moon",
    emoji: "\u{1F319}",
    name: "moon",
    displayName: "Crescent Moon",
    category: "travel",
    keywords: ["night", "sky", "sleep"],
    aliases: ["crescent_moon"],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "star2",
    emoji: "\u{1F31F}",
    name: "star2",
    displayName: "Glowing Star",
    category: "travel",
    keywords: ["night", "sky", "sparkle"],
    aliases: ["glowing_star"],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "rainbow",
    emoji: "\u{1F308}",
    name: "rainbow",
    displayName: "Rainbow",
    category: "travel",
    keywords: ["weather", "colorful", "pride"],
    aliases: [],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "ocean",
    emoji: "\u{1F30A}",
    name: "ocean",
    displayName: "Water Wave",
    category: "travel",
    keywords: ["sea", "water", "beach"],
    aliases: ["wave", "water_wave"],
    supportsSkinTone: false,
    order: 19,
  },

  // ==================== Activities ====================
  {
    id: "soccer",
    emoji: "\u{26BD}",
    name: "soccer",
    displayName: "Soccer Ball",
    category: "activities",
    keywords: ["sports", "football", "ball"],
    aliases: ["football"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "basketball",
    emoji: "\u{1F3C0}",
    name: "basketball",
    displayName: "Basketball",
    category: "activities",
    keywords: ["sports", "ball", "nba"],
    aliases: [],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "football",
    emoji: "\u{1F3C8}",
    name: "football",
    displayName: "American Football",
    category: "activities",
    keywords: ["sports", "ball", "nfl"],
    aliases: ["american_football"],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "baseball",
    emoji: "\u{26BE}",
    name: "baseball",
    displayName: "Baseball",
    category: "activities",
    keywords: ["sports", "ball", "mlb"],
    aliases: [],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "tennis",
    emoji: "\u{1F3BE}",
    name: "tennis",
    displayName: "Tennis",
    category: "activities",
    keywords: ["sports", "ball", "racket"],
    aliases: [],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "golf",
    emoji: "\u{26F3}",
    name: "golf",
    displayName: "Flag in Hole",
    category: "activities",
    keywords: ["sports", "game"],
    aliases: [],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "trophy",
    emoji: "\u{1F3C6}",
    name: "trophy",
    displayName: "Trophy",
    category: "activities",
    keywords: ["win", "award", "champion", "first", "winner"],
    aliases: ["award", "cup", "winner"],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "medal",
    emoji: "\u{1F3C5}",
    name: "medal",
    displayName: "Sports Medal",
    category: "activities",
    keywords: ["win", "award", "first"],
    aliases: ["sports_medal"],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "first_place",
    emoji: "\u{1F947}",
    name: "first_place",
    displayName: "First Place Medal",
    category: "activities",
    keywords: ["win", "gold", "first"],
    aliases: ["gold_medal"],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "video_game",
    emoji: "\u{1F3AE}",
    name: "video_game",
    displayName: "Video Game",
    category: "activities",
    keywords: ["gaming", "controller", "play"],
    aliases: ["gaming", "controller"],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "joystick",
    emoji: "\u{1F579}\u{FE0F}",
    name: "joystick",
    displayName: "Joystick",
    category: "activities",
    keywords: ["gaming", "arcade", "play"],
    aliases: [],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "dart",
    emoji: "\u{1F3AF}",
    name: "dart",
    displayName: "Bullseye",
    category: "activities",
    keywords: ["target", "goal", "focus"],
    aliases: ["bullseye", "target"],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "bowling",
    emoji: "\u{1F3B3}",
    name: "bowling",
    displayName: "Bowling",
    category: "activities",
    keywords: ["sports", "ball", "game"],
    aliases: [],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "guitar",
    emoji: "\u{1F3B8}",
    name: "guitar",
    displayName: "Guitar",
    category: "activities",
    keywords: ["music", "instrument", "rock"],
    aliases: [],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "microphone",
    emoji: "\u{1F3A4}",
    name: "microphone",
    displayName: "Microphone",
    category: "activities",
    keywords: ["music", "sing", "karaoke"],
    aliases: ["mic", "karaoke"],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "headphones",
    emoji: "\u{1F3A7}",
    name: "headphones",
    displayName: "Headphone",
    category: "activities",
    keywords: ["music", "listen", "audio"],
    aliases: ["headphone"],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "art",
    emoji: "\u{1F3A8}",
    name: "art",
    displayName: "Artist Palette",
    category: "activities",
    keywords: ["paint", "draw", "creative"],
    aliases: ["palette", "painting"],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "ticket",
    emoji: "\u{1F3AB}",
    name: "ticket",
    displayName: "Ticket",
    category: "activities",
    keywords: ["event", "admission", "movie"],
    aliases: [],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "movie",
    emoji: "\u{1F3AC}",
    name: "movie",
    displayName: "Clapper Board",
    category: "activities",
    keywords: ["film", "cinema", "action"],
    aliases: ["clapper", "film"],
    supportsSkinTone: false,
    order: 19,
  },

  // ==================== Objects ====================
  {
    id: "fire",
    emoji: "\u{1F525}",
    name: "fire",
    displayName: "Fire",
    category: "objects",
    keywords: ["hot", "flame", "lit", "burn"],
    aliases: ["flame", "hot", "lit"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "sparkles",
    emoji: "\u{2728}",
    name: "sparkles",
    displayName: "Sparkles",
    category: "objects",
    keywords: ["stars", "shine", "magic", "clean"],
    aliases: ["shine", "magic"],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "star",
    emoji: "\u{2B50}",
    name: "star",
    displayName: "Star",
    category: "objects",
    keywords: ["favorite", "gold", "award"],
    aliases: ["yellow_star"],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "zap",
    emoji: "\u{26A1}",
    name: "zap",
    displayName: "High Voltage",
    category: "objects",
    keywords: ["lightning", "electric", "energy", "thunder"],
    aliases: ["lightning", "thunder"],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "boom",
    emoji: "\u{1F4A5}",
    name: "boom",
    displayName: "Collision",
    category: "objects",
    keywords: ["explosion", "bang", "impact"],
    aliases: ["collision", "explosion"],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "100",
    emoji: "\u{1F4AF}",
    name: "100",
    displayName: "Hundred Points",
    category: "objects",
    keywords: ["perfect", "score", "century", "full"],
    aliases: ["hundred", "perfect"],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "bulb",
    emoji: "\u{1F4A1}",
    name: "bulb",
    displayName: "Light Bulb",
    category: "objects",
    keywords: ["idea", "light", "bright"],
    aliases: ["idea", "light_bulb"],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "money",
    emoji: "\u{1F4B0}",
    name: "money",
    displayName: "Money Bag",
    category: "objects",
    keywords: ["dollar", "cash", "rich", "wealth"],
    aliases: ["moneybag", "dollar"],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "gem",
    emoji: "\u{1F48E}",
    name: "gem",
    displayName: "Gem Stone",
    category: "objects",
    keywords: ["diamond", "jewel", "precious"],
    aliases: ["diamond"],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "crown",
    emoji: "\u{1F451}",
    name: "crown",
    displayName: "Crown",
    category: "objects",
    keywords: ["king", "queen", "royal"],
    aliases: ["king", "queen"],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "gift",
    emoji: "\u{1F381}",
    name: "gift",
    displayName: "Wrapped Gift",
    category: "objects",
    keywords: ["present", "birthday", "christmas"],
    aliases: ["present"],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "balloon",
    emoji: "\u{1F388}",
    name: "balloon",
    displayName: "Balloon",
    category: "objects",
    keywords: ["party", "birthday", "celebration"],
    aliases: [],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "tada",
    emoji: "\u{1F389}",
    name: "tada",
    displayName: "Party Popper",
    category: "objects",
    keywords: ["party", "celebration", "congrats", "hooray"],
    aliases: ["party", "congratulations", "congrats"],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "confetti_ball",
    emoji: "\u{1F38A}",
    name: "confetti_ball",
    displayName: "Confetti Ball",
    category: "objects",
    keywords: ["party", "celebration", "fun"],
    aliases: ["confetti"],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "bell",
    emoji: "\u{1F514}",
    name: "bell",
    displayName: "Bell",
    category: "objects",
    keywords: ["notification", "alert", "ring"],
    aliases: ["notification"],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "key",
    emoji: "\u{1F511}",
    name: "key",
    displayName: "Key",
    category: "objects",
    keywords: ["lock", "password", "security"],
    aliases: [],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "lock",
    emoji: "\u{1F512}",
    name: "lock",
    displayName: "Locked",
    category: "objects",
    keywords: ["security", "password", "private"],
    aliases: ["locked"],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "unlock",
    emoji: "\u{1F513}",
    name: "unlock",
    displayName: "Unlocked",
    category: "objects",
    keywords: ["security", "open", "public"],
    aliases: ["unlocked"],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "phone",
    emoji: "\u{1F4F1}",
    name: "phone",
    displayName: "Mobile Phone",
    category: "objects",
    keywords: ["cell", "mobile", "call", "iphone"],
    aliases: ["mobile", "iphone"],
    supportsSkinTone: false,
    order: 19,
  },
  {
    id: "computer",
    emoji: "\u{1F4BB}",
    name: "computer",
    displayName: "Laptop",
    category: "objects",
    keywords: ["laptop", "pc", "work"],
    aliases: ["laptop"],
    supportsSkinTone: false,
    order: 20,
  },
  {
    id: "keyboard",
    emoji: "\u{2328}\u{FE0F}",
    name: "keyboard",
    displayName: "Keyboard",
    category: "objects",
    keywords: ["type", "computer", "input"],
    aliases: [],
    supportsSkinTone: false,
    order: 21,
  },
  {
    id: "memo",
    emoji: "\u{1F4DD}",
    name: "memo",
    displayName: "Memo",
    category: "objects",
    keywords: ["note", "write", "document", "pencil"],
    aliases: ["note", "pencil"],
    supportsSkinTone: false,
    order: 22,
  },
  {
    id: "book",
    emoji: "\u{1F4D6}",
    name: "book",
    displayName: "Open Book",
    category: "objects",
    keywords: ["read", "library", "knowledge"],
    aliases: ["open_book"],
    supportsSkinTone: false,
    order: 23,
  },
  {
    id: "calendar",
    emoji: "\u{1F4C5}",
    name: "calendar",
    displayName: "Calendar",
    category: "objects",
    keywords: ["date", "schedule", "event"],
    aliases: [],
    supportsSkinTone: false,
    order: 24,
  },
  {
    id: "clock",
    emoji: "\u{23F0}",
    name: "clock",
    displayName: "Alarm Clock",
    category: "objects",
    keywords: ["time", "alarm", "wake"],
    aliases: ["alarm_clock"],
    supportsSkinTone: false,
    order: 25,
  },
  {
    id: "link",
    emoji: "\u{1F517}",
    name: "link",
    displayName: "Link",
    category: "objects",
    keywords: ["url", "chain", "connect"],
    aliases: ["chain"],
    supportsSkinTone: false,
    order: 26,
  },
  {
    id: "paperclip",
    emoji: "\u{1F4CE}",
    name: "paperclip",
    displayName: "Paperclip",
    category: "objects",
    keywords: ["attach", "document", "office"],
    aliases: ["attachment"],
    supportsSkinTone: false,
    order: 27,
  },
  {
    id: "gear",
    emoji: "\u{2699}\u{FE0F}",
    name: "gear",
    displayName: "Gear",
    category: "objects",
    keywords: ["settings", "cog", "options"],
    aliases: ["settings", "cog"],
    supportsSkinTone: false,
    order: 28,
  },
  {
    id: "wrench",
    emoji: "\u{1F527}",
    name: "wrench",
    displayName: "Wrench",
    category: "objects",
    keywords: ["tool", "fix", "repair"],
    aliases: ["tool"],
    supportsSkinTone: false,
    order: 29,
  },
  {
    id: "hammer",
    emoji: "\u{1F528}",
    name: "hammer",
    displayName: "Hammer",
    category: "objects",
    keywords: ["tool", "build", "fix"],
    aliases: [],
    supportsSkinTone: false,
    order: 30,
  },

  // ==================== Symbols ====================
  {
    id: "heart",
    emoji: "\u{2764}\u{FE0F}",
    name: "heart",
    displayName: "Red Heart",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: ["red_heart", "love"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "orange_heart",
    emoji: "\u{1F9E1}",
    name: "orange_heart",
    displayName: "Orange Heart",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: [],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "yellow_heart",
    emoji: "\u{1F49B}",
    name: "yellow_heart",
    displayName: "Yellow Heart",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: [],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "green_heart",
    emoji: "\u{1F49A}",
    name: "green_heart",
    displayName: "Green Heart",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: [],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "blue_heart",
    emoji: "\u{1F499}",
    name: "blue_heart",
    displayName: "Blue Heart",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: [],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "purple_heart",
    emoji: "\u{1F49C}",
    name: "purple_heart",
    displayName: "Purple Heart",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: [],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "black_heart",
    emoji: "\u{1F5A4}",
    name: "black_heart",
    displayName: "Black Heart",
    category: "symbols",
    keywords: ["love", "like", "affection", "dark"],
    aliases: [],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "white_heart",
    emoji: "\u{1F90D}",
    name: "white_heart",
    displayName: "White Heart",
    category: "symbols",
    keywords: ["love", "like", "affection", "pure"],
    aliases: [],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "broken_heart",
    emoji: "\u{1F494}",
    name: "broken_heart",
    displayName: "Broken Heart",
    category: "symbols",
    keywords: ["sad", "sorry", "heartbreak"],
    aliases: ["heartbreak"],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "two_hearts",
    emoji: "\u{1F495}",
    name: "two_hearts",
    displayName: "Two Hearts",
    category: "symbols",
    keywords: ["love", "like", "affection"],
    aliases: [],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "sparkling_heart",
    emoji: "\u{1F496}",
    name: "sparkling_heart",
    displayName: "Sparkling Heart",
    category: "symbols",
    keywords: ["love", "like", "affection", "sparkle"],
    aliases: [],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "check",
    emoji: "\u{2705}",
    name: "check",
    displayName: "Check Mark Button",
    category: "symbols",
    keywords: ["yes", "done", "complete", "ok"],
    aliases: ["white_check_mark", "done", "yes"],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "x",
    emoji: "\u{274C}",
    name: "x",
    displayName: "Cross Mark",
    category: "symbols",
    keywords: ["no", "wrong", "delete", "cancel"],
    aliases: ["cross_mark", "no", "wrong"],
    supportsSkinTone: false,
    order: 13,
  },
  {
    id: "exclamation",
    emoji: "\u{2757}",
    name: "exclamation",
    displayName: "Exclamation Mark",
    category: "symbols",
    keywords: ["important", "attention", "alert"],
    aliases: ["heavy_exclamation_mark", "important"],
    supportsSkinTone: false,
    order: 14,
  },
  {
    id: "question",
    emoji: "\u{2753}",
    name: "question",
    displayName: "Question Mark",
    category: "symbols",
    keywords: ["what", "confused", "huh"],
    aliases: ["red_question_mark"],
    supportsSkinTone: false,
    order: 15,
  },
  {
    id: "warning",
    emoji: "\u{26A0}\u{FE0F}",
    name: "warning",
    displayName: "Warning",
    category: "symbols",
    keywords: ["caution", "alert", "danger"],
    aliases: ["caution", "alert"],
    supportsSkinTone: false,
    order: 16,
  },
  {
    id: "no_entry",
    emoji: "\u{26D4}",
    name: "no_entry",
    displayName: "No Entry",
    category: "symbols",
    keywords: ["stop", "forbidden", "blocked"],
    aliases: ["stop", "forbidden"],
    supportsSkinTone: false,
    order: 17,
  },
  {
    id: "stop_sign",
    emoji: "\u{1F6D1}",
    name: "stop_sign",
    displayName: "Stop Sign",
    category: "symbols",
    keywords: ["stop", "halt", "wait"],
    aliases: ["stop"],
    supportsSkinTone: false,
    order: 18,
  },
  {
    id: "info",
    emoji: "\u{2139}\u{FE0F}",
    name: "info",
    displayName: "Information",
    category: "symbols",
    keywords: ["information", "help", "details"],
    aliases: ["information"],
    supportsSkinTone: false,
    order: 19,
  },
  {
    id: "arrow_up",
    emoji: "\u{2B06}\u{FE0F}",
    name: "arrow_up",
    displayName: "Up Arrow",
    category: "symbols",
    keywords: ["up", "direction", "north"],
    aliases: ["up"],
    supportsSkinTone: false,
    order: 20,
  },
  {
    id: "arrow_down",
    emoji: "\u{2B07}\u{FE0F}",
    name: "arrow_down",
    displayName: "Down Arrow",
    category: "symbols",
    keywords: ["down", "direction", "south"],
    aliases: ["down"],
    supportsSkinTone: false,
    order: 21,
  },
  {
    id: "arrow_left",
    emoji: "\u{2B05}\u{FE0F}",
    name: "arrow_left",
    displayName: "Left Arrow",
    category: "symbols",
    keywords: ["left", "direction", "west"],
    aliases: ["left"],
    supportsSkinTone: false,
    order: 22,
  },
  {
    id: "arrow_right",
    emoji: "\u{27A1}\u{FE0F}",
    name: "arrow_right",
    displayName: "Right Arrow",
    category: "symbols",
    keywords: ["right", "direction", "east"],
    aliases: ["right"],
    supportsSkinTone: false,
    order: 23,
  },
  {
    id: "recycle",
    emoji: "\u{267B}\u{FE0F}",
    name: "recycle",
    displayName: "Recycling Symbol",
    category: "symbols",
    keywords: ["environment", "green", "reuse"],
    aliases: ["recycling"],
    supportsSkinTone: false,
    order: 24,
  },
  {
    id: "copyright",
    emoji: "\u{00A9}\u{FE0F}",
    name: "copyright",
    displayName: "Copyright",
    category: "symbols",
    keywords: ["ip", "license", "legal"],
    aliases: [],
    supportsSkinTone: false,
    order: 25,
  },
  {
    id: "tm",
    emoji: "\u{2122}\u{FE0F}",
    name: "tm",
    displayName: "Trade Mark",
    category: "symbols",
    keywords: ["brand", "trademark", "legal"],
    aliases: ["trademark"],
    supportsSkinTone: false,
    order: 26,
  },

  // ==================== Flags ====================
  {
    id: "flag_us",
    emoji: "\u{1F1FA}\u{1F1F8}",
    name: "flag_us",
    displayName: "United States",
    category: "flags",
    keywords: ["usa", "america", "us"],
    aliases: ["us", "usa"],
    supportsSkinTone: false,
    order: 1,
  },
  {
    id: "flag_gb",
    emoji: "\u{1F1EC}\u{1F1E7}",
    name: "flag_gb",
    displayName: "United Kingdom",
    category: "flags",
    keywords: ["uk", "britain", "england"],
    aliases: ["uk", "gb"],
    supportsSkinTone: false,
    order: 2,
  },
  {
    id: "flag_ca",
    emoji: "\u{1F1E8}\u{1F1E6}",
    name: "flag_ca",
    displayName: "Canada",
    category: "flags",
    keywords: ["canada", "maple"],
    aliases: ["canada"],
    supportsSkinTone: false,
    order: 3,
  },
  {
    id: "flag_de",
    emoji: "\u{1F1E9}\u{1F1EA}",
    name: "flag_de",
    displayName: "Germany",
    category: "flags",
    keywords: ["germany", "german"],
    aliases: ["germany", "de"],
    supportsSkinTone: false,
    order: 4,
  },
  {
    id: "flag_fr",
    emoji: "\u{1F1EB}\u{1F1F7}",
    name: "flag_fr",
    displayName: "France",
    category: "flags",
    keywords: ["france", "french"],
    aliases: ["france", "fr"],
    supportsSkinTone: false,
    order: 5,
  },
  {
    id: "flag_jp",
    emoji: "\u{1F1EF}\u{1F1F5}",
    name: "flag_jp",
    displayName: "Japan",
    category: "flags",
    keywords: ["japan", "japanese"],
    aliases: ["japan", "jp"],
    supportsSkinTone: false,
    order: 6,
  },
  {
    id: "flag_cn",
    emoji: "\u{1F1E8}\u{1F1F3}",
    name: "flag_cn",
    displayName: "China",
    category: "flags",
    keywords: ["china", "chinese"],
    aliases: ["china", "cn"],
    supportsSkinTone: false,
    order: 7,
  },
  {
    id: "flag_in",
    emoji: "\u{1F1EE}\u{1F1F3}",
    name: "flag_in",
    displayName: "India",
    category: "flags",
    keywords: ["india", "indian"],
    aliases: ["india", "in"],
    supportsSkinTone: false,
    order: 8,
  },
  {
    id: "flag_br",
    emoji: "\u{1F1E7}\u{1F1F7}",
    name: "flag_br",
    displayName: "Brazil",
    category: "flags",
    keywords: ["brazil", "brazilian"],
    aliases: ["brazil", "br"],
    supportsSkinTone: false,
    order: 9,
  },
  {
    id: "flag_au",
    emoji: "\u{1F1E6}\u{1F1FA}",
    name: "flag_au",
    displayName: "Australia",
    category: "flags",
    keywords: ["australia", "aussie"],
    aliases: ["australia", "au"],
    supportsSkinTone: false,
    order: 10,
  },
  {
    id: "white_flag",
    emoji: "\u{1F3F3}\u{FE0F}",
    name: "white_flag",
    displayName: "White Flag",
    category: "flags",
    keywords: ["surrender", "peace"],
    aliases: ["surrender"],
    supportsSkinTone: false,
    order: 11,
  },
  {
    id: "rainbow_flag",
    emoji: "\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}",
    name: "rainbow_flag",
    displayName: "Rainbow Flag",
    category: "flags",
    keywords: ["pride", "lgbt", "lgbtq", "gay"],
    aliases: ["pride", "lgbtq"],
    supportsSkinTone: false,
    order: 12,
  },
  {
    id: "pirate_flag",
    emoji: "\u{1F3F4}\u{200D}\u{2620}\u{FE0F}",
    name: "pirate_flag",
    displayName: "Pirate Flag",
    category: "flags",
    keywords: ["pirate", "jolly roger", "skull"],
    aliases: ["pirate", "jolly_roger"],
    supportsSkinTone: false,
    order: 13,
  },
];

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get category information by ID
 */
export function getCategoryById(
  id: EmojiCategory,
): EmojiCategoryInfo | undefined {
  return EMOJI_CATEGORIES.find((cat) => cat.id === id);
}

/**
 * Get emojis by category
 */
export function getEmojisByCategory(category: EmojiCategory): Emoji[] {
  return EMOJI_DATA.filter((emoji) => emoji.category === category).sort(
    (a, b) => (a.order ?? 999) - (b.order ?? 999),
  );
}

/**
 * Get emoji by ID
 */
export function getEmojiById(id: string): Emoji | undefined {
  return EMOJI_DATA.find((emoji) => emoji.id === id);
}

/**
 * Get emoji by character
 */
export function getEmojiByChar(char: string): Emoji | undefined {
  return EMOJI_DATA.find((emoji) => emoji.emoji === char);
}

/**
 * Get emoji by name/shortcode
 */
export function getEmojiByName(name: string): Emoji | undefined {
  const normalizedName = name.toLowerCase().replace(/^:|:$/g, "");
  return EMOJI_DATA.find(
    (emoji) =>
      emoji.name === normalizedName || emoji.aliases.includes(normalizedName),
  );
}

/**
 * Get all emojis that support skin tones
 */
export function getSkinToneEmojis(): Emoji[] {
  return EMOJI_DATA.filter((emoji) => emoji.supportsSkinTone);
}

/**
 * Get skin tone info by value
 */
export function getSkinToneInfo(value: SkinTone): SkinToneInfo | undefined {
  return SKIN_TONES.find((tone) => tone.value === value);
}

/**
 * Create emoji lookup map for fast access
 */
export const EMOJI_BY_NAME: Map<string, Emoji> = new Map(
  EMOJI_DATA.flatMap((emoji) => [
    [emoji.name, emoji],
    ...emoji.aliases.map((alias) => [alias, emoji] as [string, Emoji]),
  ]),
);

/**
 * Create emoji lookup map by character
 */
export const EMOJI_BY_CHAR: Map<string, Emoji> = new Map(
  EMOJI_DATA.map((emoji) => [emoji.emoji, emoji]),
);

/**
 * Get total emoji count
 */
export function getEmojiCount(): number {
  return EMOJI_DATA.length;
}

/**
 * Get categories with counts
 */
export function getCategoriesWithCounts(): Array<
  EmojiCategoryInfo & { count: number }
> {
  return EMOJI_CATEGORIES.map((category) => ({
    ...category,
    count: EMOJI_DATA.filter((emoji) => emoji.category === category.id).length,
  }));
}

/**
 * Quick reaction emojis for common reactions
 */
export const QUICK_REACTIONS: Emoji[] = [
  getEmojiByChar("\u{1F44D}")!, // Thumbs up
  getEmojiByChar("\u{1F44E}")!, // Thumbs down
  getEmojiByChar("\u{2764}\u{FE0F}")!, // Red heart
  getEmojiByChar("\u{1F604}")!, // Grinning face
  getEmojiByChar("\u{1F622}")!, // Crying face
  getEmojiByChar("\u{1F389}")!, // Party popper
  getEmojiByChar("\u{1F525}")!, // Fire
  getEmojiByChar("\u{2705}")!, // Check mark
].filter(Boolean);
