/**
 * Feature Registry - Comprehensive Feature Catalog for nchat
 *
 * This module provides a complete registry of all features in the nchat application.
 * It serves as the single source of truth for feature metadata, status, and dependencies.
 *
 * @module feature-registry
 * @version 1.0.0
 * @since 2026-02-03
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

/**
 * Feature categories aligned with the parity matrix structure
 */
export type FeatureCategory =
  | 'messaging'
  | 'channels'
  | 'presence'
  | 'media'
  | 'search'
  | 'notifications'
  | 'authentication'
  | 'e2ee'
  | 'moderation'
  | 'billing'
  | 'voice_video'
  | 'streaming'
  | 'integrations'
  | 'admin'
  | 'compliance'
  | 'platform'

/**
 * Implementation status of a feature
 */
export type FeatureStatus = 'not_started' | 'in_progress' | 'complete' | 'blocked'

/**
 * Plan levels for feature restrictions
 */
export type PlanLevel = 'free' | 'starter' | 'pro' | 'business' | 'enterprise'

/**
 * Platform compatibility for platform-specific features
 */
export type Platform = 'web' | 'ios' | 'android' | 'macos' | 'windows' | 'linux'

/**
 * Feature definition interface
 */
export interface Feature {
  /** Unique identifier for the feature (kebab-case) */
  id: string
  /** Human-readable feature name */
  name: string
  /** Category grouping */
  category: FeatureCategory
  /** Detailed description of the feature */
  description: string
  /** Current implementation status */
  status: FeatureStatus
  /** IDs of features this depends on */
  dependencies: string[]
  /** Whether this feature is enforced server-side */
  backend_enforced: boolean
  /** Plan levels that have access (empty = all plans) */
  plan_restrictions: PlanLevel[]
  /** Feature flag paths (e.g., 'messaging.threads') */
  flags: string[]
  /** UI component path (e.g., 'src/components/chat/ThreadView') */
  ui_component?: string
  /** API endpoint path */
  api_endpoint?: string
  /** Database tables used */
  db_tables?: string[]
  /** Realtime events emitted/consumed */
  realtime_events?: string[]
  /** Test file path */
  test_file?: string
  /** Platform restrictions (empty = all platforms) */
  platforms?: Platform[]
  /** Phase number from the development roadmap */
  phase?: number
  /** Priority (1-5, 1 being highest) */
  priority?: number
}

// =============================================================================
// FEATURE REGISTRY
// =============================================================================

/**
 * Complete feature registry containing all nchat features
 * Organized by category for easier maintenance
 */
export const FEATURE_REGISTRY: readonly Feature[] = [
  // ===========================================================================
  // MESSAGING FEATURES (Phase 5)
  // ===========================================================================
  {
    id: 'msg-send-text',
    name: 'Send Text Message',
    category: 'messaging',
    description: 'Send text messages to channels and DMs with full formatting support',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/MessageInput',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages'],
    realtime_events: ['message:created'],
    test_file: 'src/app/api/__tests__/messages.test.ts',
    phase: 5,
    priority: 1,
  },
  {
    id: 'msg-edit',
    name: 'Edit Message',
    category: 'messaging',
    description: 'Edit previously sent messages with edit history tracking',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.editing'],
    ui_component: 'src/components/chat/MessageEditForm',
    api_endpoint: 'PATCH /api/messages/:id',
    db_tables: ['nchat_messages', 'nchat_message_edits'],
    realtime_events: ['message:updated'],
    test_file: 'src/app/api/__tests__/messages.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-delete',
    name: 'Delete Message',
    category: 'messaging',
    description: 'Delete messages with soft-delete for compliance',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.deletion'],
    ui_component: 'src/components/chat/MessageActions',
    api_endpoint: 'DELETE /api/messages/:id',
    db_tables: ['nchat_messages'],
    realtime_events: ['message:deleted'],
    test_file: 'src/app/api/__tests__/messages.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-formatting',
    name: 'Message Formatting',
    category: 'messaging',
    description: 'Rich text formatting with Markdown support via TipTap editor',
    status: 'complete',
    dependencies: ['msg-send-text'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/RichTextEditor',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages'],
    realtime_events: ['message:created'],
    test_file: 'src/components/chat/__tests__/rich-text.test.tsx',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-code-blocks',
    name: 'Code Blocks',
    category: 'messaging',
    description: 'Syntax-highlighted code blocks with language detection',
    status: 'complete',
    dependencies: ['msg-formatting'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/CodeBlock',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages'],
    realtime_events: ['message:created'],
    test_file: 'src/components/chat/__tests__/code-blocks.test.tsx',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-mentions',
    name: 'User Mentions',
    category: 'messaging',
    description: 'Mention users with @username autocomplete and notifications',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/MentionSuggestions',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages', 'nchat_mentions'],
    realtime_events: ['mention:created'],
    test_file: 'src/graphql/__tests__/mentions.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-channel-mentions',
    name: 'Channel Mentions',
    category: 'messaging',
    description: 'Mention @channel or @here to notify all channel members',
    status: 'not_started',
    dependencies: ['msg-mentions'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/MentionSuggestions',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages', 'nchat_mentions'],
    realtime_events: ['mention:created'],
    test_file: 'src/graphql/__tests__/mentions.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-link-preview',
    name: 'Link Previews',
    category: 'messaging',
    description: 'Automatic URL unfurling with Open Graph metadata extraction',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/LinkPreview',
    api_endpoint: 'GET /api/link-preview',
    db_tables: ['nchat_link_previews'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/link-preview.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-reactions',
    name: 'Emoji Reactions',
    category: 'messaging',
    description: 'React to messages with emoji including custom emoji support',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.reactions'],
    ui_component: 'src/components/chat/ReactionPicker',
    api_endpoint: 'POST /api/messages/:id/reactions',
    db_tables: ['nchat_reactions'],
    realtime_events: ['reaction:added', 'reaction:removed'],
    test_file: 'src/graphql/__tests__/reactions.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-custom-emoji',
    name: 'Custom Emoji Reactions',
    category: 'messaging',
    description: 'Upload and use custom emoji for reactions',
    status: 'not_started',
    dependencies: ['msg-reactions'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['features.customEmojis'],
    ui_component: 'src/components/chat/CustomEmojiPicker',
    api_endpoint: 'POST /api/emoji',
    db_tables: ['nchat_reactions', 'nchat_custom_emojis'],
    realtime_events: ['reaction:added'],
    test_file: 'src/app/api/__tests__/custom-emoji.test.ts',
    phase: 5,
    priority: 4,
  },
  {
    id: 'msg-reply',
    name: 'Reply to Message',
    category: 'messaging',
    description: 'Reply to specific messages with visual threading',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.replies'],
    ui_component: 'src/components/chat/ReplyPreview',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages'],
    realtime_events: ['message:created'],
    test_file: 'src/graphql/__tests__/replies.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-quote',
    name: 'Quote Message',
    category: 'messaging',
    description: 'Quote messages with visual block quote formatting',
    status: 'not_started',
    dependencies: ['msg-reply'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['messaging.replies'],
    ui_component: 'src/components/chat/QuoteBlock',
    api_endpoint: 'POST /api/messages',
    db_tables: ['nchat_messages'],
    realtime_events: ['message:created'],
    test_file: 'src/graphql/__tests__/quotes.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-forward',
    name: 'Forward Message',
    category: 'messaging',
    description: 'Forward messages to other channels or users',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.forwarding'],
    ui_component: 'src/components/chat/ForwardModal',
    api_endpoint: 'POST /api/messages/forward',
    db_tables: ['nchat_messages', 'nchat_forwards'],
    realtime_events: ['message:forwarded'],
    test_file: 'src/graphql/__tests__/forward.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-pin',
    name: 'Pin Message',
    category: 'messaging',
    description: 'Pin important messages to channel for easy access',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/PinnedMessages',
    api_endpoint: 'POST /api/messages/:id/pin',
    db_tables: ['nchat_pinned_messages'],
    realtime_events: ['message:pinned'],
    test_file: 'src/graphql/__tests__/pinned.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-bookmark',
    name: 'Bookmark Message',
    category: 'messaging',
    description: 'Save messages to personal bookmarks collection',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/BookmarksList',
    api_endpoint: 'POST /api/bookmarks',
    db_tables: ['nchat_bookmarks'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/bookmarks.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-threads',
    name: 'Threaded Replies',
    category: 'messaging',
    description: 'Create threaded conversations from any message',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.threads'],
    ui_component: 'src/components/chat/ThreadView',
    api_endpoint: 'POST /api/threads/:id/messages',
    db_tables: ['nchat_messages', 'nchat_threads'],
    realtime_events: ['thread:message:created'],
    test_file: 'src/graphql/__tests__/threads.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'msg-thread-notifications',
    name: 'Thread Notifications',
    category: 'messaging',
    description: 'Subscribe to thread updates and receive notifications',
    status: 'not_started',
    dependencies: ['msg-threads'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.threads'],
    ui_component: 'src/components/chat/ThreadNotificationSettings',
    api_endpoint: 'POST /api/threads/:id/subscribe',
    db_tables: ['nchat_thread_subscriptions'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/threads.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'msg-scheduled',
    name: 'Scheduled Messages',
    category: 'messaging',
    description: 'Schedule messages to be sent at a future time',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['messaging.scheduling'],
    ui_component: 'src/components/chat/ScheduleMessageModal',
    api_endpoint: 'POST /api/messages/schedule',
    db_tables: ['nchat_scheduled_messages'],
    realtime_events: ['message:scheduled'],
    test_file: 'src/app/api/__tests__/scheduled.test.ts',
    phase: 5,
    priority: 4,
  },
  {
    id: 'msg-disappearing',
    name: 'Disappearing Messages',
    category: 'messaging',
    description: 'Messages that auto-delete after a configurable time',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.disappearing'],
    ui_component: 'src/components/chat/DisappearingSettings',
    api_endpoint: 'POST /api/channels/:id/disappearing',
    db_tables: ['nchat_disappearing_settings'],
    realtime_events: ['message:expired'],
    test_file: 'src/graphql/__tests__/disappearing.test.ts',
    phase: 5,
    priority: 4,
  },
  {
    id: 'msg-edit-history',
    name: 'Message Edit History',
    category: 'messaging',
    description: 'View complete edit history of any message',
    status: 'not_started',
    dependencies: ['msg-edit'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.editing'],
    ui_component: 'src/components/chat/EditHistoryModal',
    api_endpoint: 'GET /api/messages/:id/history',
    db_tables: ['nchat_message_edits'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/edit-history.test.ts',
    phase: 5,
    priority: 4,
  },
  {
    id: 'msg-translate',
    name: 'Message Translation',
    category: 'messaging',
    description: 'Translate messages to different languages',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/TranslateButton',
    api_endpoint: 'POST /api/translate',
    db_tables: ['nchat_translations'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/translate.test.ts',
    phase: 5,
    priority: 5,
  },
  {
    id: 'msg-polls',
    name: 'Polls',
    category: 'messaging',
    description: 'Create polls with multiple choice options',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['messaging.enabled'],
    ui_component: 'src/components/chat/PollCreator',
    api_endpoint: 'POST /api/polls',
    db_tables: ['nchat_polls', 'nchat_poll_options', 'nchat_poll_votes'],
    realtime_events: ['poll:vote:added'],
    test_file: 'src/app/api/__tests__/polls.test.ts',
    phase: 5,
    priority: 3,
  },

  // ===========================================================================
  // CHANNEL FEATURES (Phase 6)
  // ===========================================================================
  {
    id: 'chan-public',
    name: 'Public Channels',
    category: 'channels',
    description: 'Create public channels visible to all workspace members',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.public'],
    ui_component: 'src/components/chat/ChannelList',
    api_endpoint: 'POST /api/channels',
    db_tables: ['nchat_channels'],
    realtime_events: ['channel:created'],
    test_file: 'src/app/api/__tests__/channels.test.ts',
    phase: 6,
    priority: 1,
  },
  {
    id: 'chan-private',
    name: 'Private Channels',
    category: 'channels',
    description: 'Create invite-only private channels',
    status: 'in_progress',
    dependencies: ['chan-public'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.private'],
    ui_component: 'src/components/chat/PrivateChannelModal',
    api_endpoint: 'POST /api/channels',
    db_tables: ['nchat_channels'],
    realtime_events: ['channel:created'],
    test_file: 'src/app/api/__tests__/channels.test.ts',
    phase: 6,
    priority: 1,
  },
  {
    id: 'chan-dm',
    name: 'Direct Messages',
    category: 'channels',
    description: 'One-on-one private messaging between users',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.directMessages'],
    ui_component: 'src/components/chat/DMList',
    api_endpoint: 'POST /api/dms',
    db_tables: ['nchat_direct_messages', 'nchat_dm_participants'],
    realtime_events: ['dm:created'],
    test_file: 'src/graphql/__tests__/dms.test.ts',
    phase: 6,
    priority: 1,
  },
  {
    id: 'chan-group-dm',
    name: 'Group Direct Messages',
    category: 'channels',
    description: 'Private group conversations with 3+ users',
    status: 'not_started',
    dependencies: ['chan-dm'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.groupDms'],
    ui_component: 'src/components/chat/GroupDMModal',
    api_endpoint: 'POST /api/dms',
    db_tables: ['nchat_direct_messages', 'nchat_dm_participants'],
    realtime_events: ['dm:created'],
    test_file: 'src/graphql/__tests__/dms.test.ts',
    phase: 6,
    priority: 2,
  },
  {
    id: 'chan-broadcast',
    name: 'Broadcast Channels',
    category: 'channels',
    description: 'One-way announcement channels with restricted posting',
    status: 'not_started',
    dependencies: ['chan-public'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['channels.public'],
    ui_component: 'src/components/chat/BroadcastChannel',
    api_endpoint: 'POST /api/channels',
    db_tables: ['nchat_channels'],
    realtime_events: ['channel:created'],
    test_file: 'src/app/api/__tests__/broadcast.test.ts',
    phase: 6,
    priority: 3,
  },
  {
    id: 'chan-categories',
    name: 'Channel Categories',
    category: 'channels',
    description: 'Organize channels into collapsible categories',
    status: 'not_started',
    dependencies: ['chan-public'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.categories'],
    ui_component: 'src/components/chat/CategoryList',
    api_endpoint: 'POST /api/categories',
    db_tables: ['nchat_categories'],
    realtime_events: ['category:created'],
    test_file: 'src/app/api/__tests__/categories.test.ts',
    phase: 6,
    priority: 3,
  },
  {
    id: 'chan-ordering',
    name: 'Channel Ordering',
    category: 'channels',
    description: 'Drag and drop channel reordering',
    status: 'not_started',
    dependencies: ['chan-public'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.categories'],
    ui_component: 'src/components/chat/DraggableChannel',
    api_endpoint: 'PATCH /api/channels/:id/order',
    db_tables: ['nchat_channels'],
    realtime_events: ['channel:reordered'],
    test_file: 'src/app/api/__tests__/order.test.ts',
    phase: 6,
    priority: 4,
  },
  {
    id: 'chan-servers',
    name: 'Servers/Workspaces',
    category: 'channels',
    description: 'Discord-style server hierarchy with multiple workspaces',
    status: 'not_started',
    dependencies: ['chan-public', 'chan-categories'],
    backend_enforced: true,
    plan_restrictions: ['business', 'enterprise'],
    flags: ['servers.enabled'],
    ui_component: 'src/components/chat/ServerSidebar',
    api_endpoint: 'POST /api/servers',
    db_tables: ['nchat_servers'],
    realtime_events: ['server:created'],
    test_file: 'src/app/api/__tests__/servers.test.ts',
    phase: 6,
    priority: 4,
  },
  {
    id: 'chan-invites',
    name: 'Invite Links',
    category: 'channels',
    description: 'Generate shareable invite links with optional expiry',
    status: 'in_progress',
    dependencies: ['chan-public'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['features.inviteLinks'],
    ui_component: 'src/components/chat/InviteLinkModal',
    api_endpoint: 'POST /api/invites',
    db_tables: ['nchat_invites'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/invites.test.ts',
    phase: 6,
    priority: 2,
  },
  {
    id: 'chan-members',
    name: 'Member Management',
    category: 'channels',
    description: 'View and manage channel members with role assignment',
    status: 'in_progress',
    dependencies: ['chan-public'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['channels.public'],
    ui_component: 'src/components/chat/MemberList',
    api_endpoint: 'GET /api/channels/:id/members',
    db_tables: ['nchat_channel_members'],
    realtime_events: ['member:joined', 'member:removed'],
    test_file: 'src/app/api/__tests__/members.test.ts',
    phase: 6,
    priority: 2,
  },
  {
    id: 'chan-permissions',
    name: 'Channel Permissions',
    category: 'channels',
    description: 'Fine-grained permission overrides per channel',
    status: 'not_started',
    dependencies: ['chan-public', 'chan-members'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['channels.public'],
    ui_component: 'src/components/chat/PermissionEditor',
    api_endpoint: 'PATCH /api/channels/:id/permissions',
    db_tables: ['nchat_channel_permissions'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/permissions.test.ts',
    phase: 6,
    priority: 3,
  },

  // ===========================================================================
  // PRESENCE FEATURES (Phase 7)
  // ===========================================================================
  {
    id: 'pres-online',
    name: 'Online Status',
    category: 'presence',
    description: 'Real-time online/offline presence indicators',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/ui/PresenceIndicator',
    api_endpoint: 'POST /api/presence',
    db_tables: ['nchat_presence'],
    realtime_events: ['presence:updated'],
    test_file: 'src/graphql/__tests__/presence.test.ts',
    phase: 7,
    priority: 1,
  },
  {
    id: 'pres-away',
    name: 'Away Status',
    category: 'presence',
    description: 'Manual or automatic away status after inactivity',
    status: 'not_started',
    dependencies: ['pres-online'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/ui/StatusSelector',
    api_endpoint: 'POST /api/presence',
    db_tables: ['nchat_presence'],
    realtime_events: ['presence:updated'],
    test_file: 'src/graphql/__tests__/presence.test.ts',
    phase: 7,
    priority: 2,
  },
  {
    id: 'pres-dnd',
    name: 'Do Not Disturb',
    category: 'presence',
    description: 'DND mode that suppresses all notifications',
    status: 'not_started',
    dependencies: ['pres-online'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/ui/DNDSettings',
    api_endpoint: 'POST /api/presence',
    db_tables: ['nchat_presence'],
    realtime_events: ['presence:updated'],
    test_file: 'src/graphql/__tests__/presence.test.ts',
    phase: 7,
    priority: 3,
  },
  {
    id: 'pres-custom',
    name: 'Custom Status',
    category: 'presence',
    description: 'Set custom status text with optional emoji and expiry',
    status: 'not_started',
    dependencies: ['pres-online'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/ui/CustomStatusInput',
    api_endpoint: 'POST /api/presence',
    db_tables: ['nchat_presence'],
    realtime_events: ['presence:updated'],
    test_file: 'src/graphql/__tests__/presence.test.ts',
    phase: 7,
    priority: 3,
  },
  {
    id: 'pres-typing',
    name: 'Typing Indicators',
    category: 'presence',
    description: 'Show when users are typing in channels/DMs',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/chat/TypingIndicator',
    api_endpoint: undefined,
    db_tables: [],
    realtime_events: ['typing:started', 'typing:stopped'],
    test_file: 'src/graphql/__tests__/typing.test.ts',
    phase: 7,
    priority: 1,
  },
  {
    id: 'pres-read-receipts',
    name: 'Read Receipts',
    category: 'presence',
    description: 'Track and display when messages have been read',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/chat/ReadReceipts',
    api_endpoint: 'POST /api/messages/:id/read',
    db_tables: ['nchat_read_receipts'],
    realtime_events: ['message:read'],
    test_file: 'src/graphql/__tests__/read-receipts.test.ts',
    phase: 7,
    priority: 2,
  },
  {
    id: 'pres-delivery-receipts',
    name: 'Delivery Receipts',
    category: 'presence',
    description: 'Track when messages have been delivered to recipients',
    status: 'not_started',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['presence.enabled'],
    ui_component: 'src/components/chat/DeliveryStatus',
    api_endpoint: 'POST /api/messages/:id/delivered',
    db_tables: ['nchat_delivery_receipts'],
    realtime_events: ['message:delivered'],
    test_file: 'src/graphql/__tests__/receipts.test.ts',
    phase: 7,
    priority: 3,
  },

  // ===========================================================================
  // MEDIA FEATURES (Phase 5)
  // ===========================================================================
  {
    id: 'media-image-upload',
    name: 'Image Upload',
    category: 'media',
    description: 'Upload images with automatic compression and thumbnail generation',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['media.imageUploads'],
    ui_component: 'src/components/chat/ImageUploader',
    api_endpoint: 'POST /api/storage',
    db_tables: ['nchat_attachments'],
    realtime_events: ['attachment:uploaded'],
    test_file: 'src/app/api/__tests__/upload.test.ts',
    phase: 5,
    priority: 1,
  },
  {
    id: 'media-video-upload',
    name: 'Video Upload',
    category: 'media',
    description: 'Upload videos with transcoding and thumbnail extraction',
    status: 'in_progress',
    dependencies: ['media-image-upload'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['media.videoUploads'],
    ui_component: 'src/components/chat/VideoUploader',
    api_endpoint: 'POST /api/storage',
    db_tables: ['nchat_attachments'],
    realtime_events: ['attachment:uploaded'],
    test_file: 'src/app/api/__tests__/upload.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'media-file-upload',
    name: 'File Upload',
    category: 'media',
    description: 'Upload arbitrary files with virus scanning',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['media.fileUploads'],
    ui_component: 'src/components/chat/FileUploader',
    api_endpoint: 'POST /api/storage',
    db_tables: ['nchat_attachments'],
    realtime_events: ['attachment:uploaded'],
    test_file: 'src/app/api/__tests__/upload.test.ts',
    phase: 5,
    priority: 2,
  },
  {
    id: 'media-voice-messages',
    name: 'Voice Messages',
    category: 'media',
    description: 'Record and send voice messages with waveform visualization',
    status: 'not_started',
    dependencies: ['media-file-upload'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['voice.voiceMessages'],
    ui_component: 'src/components/chat/VoiceRecorder',
    api_endpoint: 'POST /api/storage',
    db_tables: ['nchat_attachments'],
    realtime_events: ['attachment:uploaded'],
    test_file: 'src/app/api/__tests__/voice.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'media-gif',
    name: 'GIF Support',
    category: 'media',
    description: 'Search and send GIFs via Giphy/Tenor integration',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['features.gifs'],
    ui_component: 'src/components/chat/GifPicker',
    api_endpoint: 'GET /api/gif',
    db_tables: [],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/gif.test.ts',
    phase: 5,
    priority: 3,
  },
  {
    id: 'media-stickers',
    name: 'Stickers',
    category: 'media',
    description: 'Send stickers from built-in and custom sticker packs',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['features.stickers'],
    ui_component: 'src/components/chat/StickerPicker',
    api_endpoint: 'GET /api/stickers',
    db_tables: ['nchat_sticker_packs', 'nchat_stickers'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/stickers.test.ts',
    phase: 5,
    priority: 4,
  },
  {
    id: 'media-gallery',
    name: 'Media Gallery',
    category: 'media',
    description: 'View all media shared in a channel/DM',
    status: 'not_started',
    dependencies: ['media-image-upload', 'media-video-upload'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['media.imageUploads'],
    ui_component: 'src/components/chat/MediaGallery',
    api_endpoint: 'GET /api/channels/:id/media',
    db_tables: ['nchat_attachments'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/gallery.test.ts',
    phase: 5,
    priority: 3,
  },

  // ===========================================================================
  // SEARCH FEATURES (Phase 14)
  // ===========================================================================
  {
    id: 'search-messages',
    name: 'Message Search',
    category: 'search',
    description: 'Full-text search across all messages via MeiliSearch',
    status: 'in_progress',
    dependencies: ['msg-send-text'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['features.search'],
    ui_component: 'src/components/chat/SearchBar',
    api_endpoint: 'GET /api/search',
    db_tables: ['nchat_messages'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/search.test.ts',
    phase: 14,
    priority: 1,
  },
  {
    id: 'search-filters',
    name: 'Search Filters',
    category: 'search',
    description: 'Filter search results by channel, user, date, and more',
    status: 'not_started',
    dependencies: ['search-messages'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['features.search'],
    ui_component: 'src/components/chat/SearchFilters',
    api_endpoint: 'GET /api/search',
    db_tables: [],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/filters.test.ts',
    phase: 14,
    priority: 2,
  },
  {
    id: 'search-ai',
    name: 'AI-Powered Search',
    category: 'search',
    description: 'Semantic search using AI embeddings',
    status: 'in_progress',
    dependencies: ['search-messages'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['ai.search'],
    ui_component: 'src/components/chat/AISearch',
    api_endpoint: 'GET /api/ai/search',
    db_tables: ['nchat_embeddings'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/ai-search.test.ts',
    phase: 14,
    priority: 3,
  },

  // ===========================================================================
  // NOTIFICATION FEATURES (Phase 11)
  // ===========================================================================
  {
    id: 'notif-push',
    name: 'Push Notifications',
    category: 'notifications',
    description: 'Native push notifications on all platforms',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['notifications.push'],
    ui_component: 'src/components/settings/PushSettings',
    api_endpoint: 'POST /api/notifications/subscribe',
    db_tables: ['nchat_push_subscriptions'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/push.test.ts',
    phase: 11,
    priority: 1,
  },
  {
    id: 'notif-email',
    name: 'Email Notifications',
    category: 'notifications',
    description: 'Email notifications for mentions, DMs, and digests',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['notifications.email'],
    ui_component: 'src/components/settings/EmailSettings',
    api_endpoint: 'PATCH /api/settings',
    db_tables: ['nchat_user_settings'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/email.test.ts',
    phase: 11,
    priority: 2,
  },
  {
    id: 'notif-inapp',
    name: 'In-App Notifications',
    category: 'notifications',
    description: 'Real-time in-app notification center',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['notifications.enabled'],
    ui_component: 'src/components/layout/NotificationCenter',
    api_endpoint: 'GET /api/notifications',
    db_tables: ['nchat_notifications'],
    realtime_events: ['notification:created'],
    test_file: 'src/graphql/__tests__/notifications.test.ts',
    phase: 11,
    priority: 1,
  },
  {
    id: 'notif-preferences',
    name: 'Notification Preferences',
    category: 'notifications',
    description: 'Granular control over notification types and channels',
    status: 'not_started',
    dependencies: ['notif-inapp'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['notifications.enabled'],
    ui_component: 'src/components/settings/NotificationSettings',
    api_endpoint: 'PATCH /api/settings',
    db_tables: ['nchat_user_settings'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/settings.test.ts',
    phase: 11,
    priority: 2,
  },
  {
    id: 'notif-reminders',
    name: 'Reminders',
    category: 'notifications',
    description: 'Set reminders on messages to follow up later',
    status: 'not_started',
    dependencies: ['notif-inapp'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['notifications.enabled'],
    ui_component: 'src/components/chat/ReminderModal',
    api_endpoint: 'POST /api/reminders',
    db_tables: ['nchat_reminders'],
    realtime_events: ['reminder:triggered'],
    test_file: 'src/graphql/__tests__/reminders.test.ts',
    phase: 11,
    priority: 3,
  },

  // ===========================================================================
  // AUTHENTICATION FEATURES (Phase 10)
  // ===========================================================================
  {
    id: 'auth-email-password',
    name: 'Email/Password Login',
    category: 'authentication',
    description: 'Traditional email and password authentication',
    status: 'complete',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['authProviders.emailPassword'],
    ui_component: 'src/components/auth/LoginForm',
    api_endpoint: 'POST /api/auth/signin',
    db_tables: ['nchat_users'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/auth.test.ts',
    phase: 10,
    priority: 1,
  },
  {
    id: 'auth-magic-link',
    name: 'Magic Links',
    category: 'authentication',
    description: 'Passwordless login via email magic links',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['authProviders.magicLinks'],
    ui_component: 'src/components/auth/MagicLinkForm',
    api_endpoint: 'POST /api/auth/magic-link',
    db_tables: ['nchat_magic_links'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/magic-link.test.ts',
    phase: 10,
    priority: 3,
  },
  {
    id: 'auth-oauth-google',
    name: 'Google OAuth',
    category: 'authentication',
    description: 'Sign in with Google account',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['authProviders.google'],
    ui_component: 'src/components/auth/GoogleLoginButton',
    api_endpoint: 'GET /api/auth/oauth/connect?provider=google',
    db_tables: ['nchat_oauth_accounts'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/oauth.test.ts',
    phase: 10,
    priority: 2,
  },
  {
    id: 'auth-oauth-github',
    name: 'GitHub OAuth',
    category: 'authentication',
    description: 'Sign in with GitHub account',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['authProviders.github'],
    ui_component: 'src/components/auth/GitHubLoginButton',
    api_endpoint: 'GET /api/auth/oauth/connect?provider=github',
    db_tables: ['nchat_oauth_accounts'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/oauth.test.ts',
    phase: 10,
    priority: 2,
  },
  {
    id: 'auth-oauth-discord',
    name: 'Discord OAuth',
    category: 'authentication',
    description: 'Sign in with Discord account',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['authProviders.discord'],
    ui_component: 'src/components/auth/DiscordLoginButton',
    api_endpoint: 'GET /api/auth/oauth/connect?provider=discord',
    db_tables: ['nchat_oauth_accounts'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/oauth.test.ts',
    phase: 10,
    priority: 3,
  },
  {
    id: 'auth-idme',
    name: 'ID.me Verification',
    category: 'authentication',
    description: 'Identity verification for military, police, and government',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['authProviders.idme.enabled'],
    ui_component: 'src/components/auth/IDmeButton',
    api_endpoint: 'GET /api/auth/oauth/connect?provider=idme',
    db_tables: ['nchat_oauth_accounts', 'nchat_idme_verifications'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/idme.test.ts',
    phase: 10,
    priority: 4,
  },
  {
    id: 'auth-2fa',
    name: 'Two-Factor Authentication',
    category: 'authentication',
    description: 'TOTP-based 2FA with backup codes',
    status: 'in_progress',
    dependencies: ['auth-email-password'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['security.twoFactor'],
    ui_component: 'src/components/auth/TwoFactorSetup',
    api_endpoint: 'POST /api/auth/2fa/setup',
    db_tables: ['nchat_2fa_secrets', 'nchat_backup_codes'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/2fa.test.ts',
    phase: 10,
    priority: 2,
  },
  {
    id: 'auth-sessions',
    name: 'Session Management',
    category: 'authentication',
    description: 'View and revoke active sessions',
    status: 'in_progress',
    dependencies: ['auth-email-password'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['security.sessionManagement'],
    ui_component: 'src/components/settings/SessionList',
    api_endpoint: 'GET /api/auth/sessions',
    db_tables: ['nchat_sessions'],
    realtime_events: ['session:revoked'],
    test_file: 'src/app/api/__tests__/sessions.test.ts',
    phase: 10,
    priority: 2,
  },
  {
    id: 'auth-sso-saml',
    name: 'SAML SSO',
    category: 'authentication',
    description: 'Enterprise SAML single sign-on',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['enterprise'],
    flags: ['enterprise.sso.enabled'],
    ui_component: 'src/components/auth/SAMLLoginButton',
    api_endpoint: 'GET /api/auth/saml',
    db_tables: ['nchat_sso_configurations'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/saml.test.ts',
    phase: 10,
    priority: 5,
  },

  // ===========================================================================
  // E2EE FEATURES (Phase 9)
  // ===========================================================================
  {
    id: 'e2ee-init',
    name: 'E2EE Initialization',
    category: 'e2ee',
    description: 'Initialize end-to-end encryption for a user',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['security.e2eEncryption'],
    ui_component: 'src/components/e2ee/E2EESetup',
    api_endpoint: 'POST /api/e2ee/initialize',
    db_tables: ['nchat_e2ee_keys'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/e2ee.test.ts',
    phase: 9,
    priority: 1,
  },
  {
    id: 'e2ee-key-exchange',
    name: 'Key Exchange',
    category: 'e2ee',
    description: 'Signal Protocol key exchange between users',
    status: 'not_started',
    dependencies: ['e2ee-init'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['security.e2eEncryption'],
    ui_component: 'src/components/e2ee/KeyExchangeView',
    api_endpoint: 'POST /api/e2ee/keys/exchange',
    db_tables: ['nchat_e2ee_sessions'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/e2ee.test.ts',
    phase: 9,
    priority: 1,
  },
  {
    id: 'e2ee-safety-numbers',
    name: 'Safety Numbers',
    category: 'e2ee',
    description: 'Verify encryption keys via safety numbers and QR codes',
    status: 'not_started',
    dependencies: ['e2ee-key-exchange'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['encryption.enableSafetyNumbers'],
    ui_component: 'src/components/e2ee/SafetyNumberView',
    api_endpoint: 'GET /api/e2ee/safety-number/:userId',
    db_tables: ['nchat_e2ee_sessions'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/safety.test.ts',
    phase: 9,
    priority: 2,
  },
  {
    id: 'e2ee-key-backup',
    name: 'Key Backup',
    category: 'e2ee',
    description: 'Securely backup encryption keys for recovery',
    status: 'not_started',
    dependencies: ['e2ee-init'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['security.e2eEncryption'],
    ui_component: 'src/components/e2ee/KeyBackupSetup',
    api_endpoint: 'POST /api/e2ee/backup',
    db_tables: ['nchat_e2ee_backups'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/backup.test.ts',
    phase: 9,
    priority: 2,
  },
  {
    id: 'e2ee-key-recovery',
    name: 'Key Recovery',
    category: 'e2ee',
    description: 'Recover encryption keys from backup',
    status: 'not_started',
    dependencies: ['e2ee-key-backup'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['security.e2eEncryption'],
    ui_component: 'src/components/e2ee/KeyRecoveryFlow',
    api_endpoint: 'POST /api/e2ee/recover',
    db_tables: ['nchat_e2ee_keys'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/recovery.test.ts',
    phase: 9,
    priority: 2,
  },
  {
    id: 'e2ee-device-lock',
    name: 'Device Lock',
    category: 'e2ee',
    description: 'PIN and biometric device security',
    status: 'not_started',
    dependencies: [],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['security.pinLock', 'security.biometricLock'],
    ui_component: 'src/components/e2ee/PINLockScreen',
    api_endpoint: undefined,
    db_tables: [],
    realtime_events: [],
    test_file: 'src/components/e2ee/__tests__/pin-lock.test.tsx',
    platforms: ['ios', 'android', 'macos', 'windows'],
    phase: 9,
    priority: 3,
  },

  // ===========================================================================
  // MODERATION FEATURES (Phase 13)
  // ===========================================================================
  {
    id: 'mod-profanity',
    name: 'Profanity Filter',
    category: 'moderation',
    description: 'Automatic profanity detection and filtering',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['moderation.profanityFilter'],
    ui_component: 'src/components/admin/ProfanitySettings',
    api_endpoint: 'POST /api/moderation/scan',
    db_tables: ['nchat_moderation_rules'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/moderation-routes.test.ts',
    phase: 13,
    priority: 2,
  },
  {
    id: 'mod-spam',
    name: 'Spam Detection',
    category: 'moderation',
    description: 'AI-powered spam detection and prevention',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['moderation.spamDetection'],
    ui_component: 'src/components/admin/SpamSettings',
    api_endpoint: 'POST /api/moderation/scan',
    db_tables: ['nchat_moderation_rules'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/moderation-routes.test.ts',
    phase: 13,
    priority: 2,
  },
  {
    id: 'mod-ai',
    name: 'AI Moderation',
    category: 'moderation',
    description: 'AI-powered content moderation for toxicity and NSFW',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['moderation.aiModeration.enabled'],
    ui_component: 'src/components/admin/AIModerationSettings',
    api_endpoint: 'POST /api/moderation/scan',
    db_tables: ['nchat_moderation_results'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/moderation-routes.test.ts',
    phase: 13,
    priority: 3,
  },
  {
    id: 'mod-reports',
    name: 'User Reports',
    category: 'moderation',
    description: 'User reporting system for messages, users, and channels',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['moderation.reportingSystem'],
    ui_component: 'src/components/chat/ReportMessageButton',
    api_endpoint: 'POST /api/reports',
    db_tables: ['nchat_reports'],
    realtime_events: ['report:created'],
    test_file: 'src/graphql/__tests__/reports.test.ts',
    phase: 13,
    priority: 2,
  },
  {
    id: 'mod-queue',
    name: 'Moderation Queue',
    category: 'moderation',
    description: 'Admin queue for reviewing flagged content',
    status: 'not_started',
    dependencies: ['mod-reports'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['moderation.reportingSystem'],
    ui_component: 'src/components/admin/ModerationQueue',
    api_endpoint: 'GET /api/moderation/queue',
    db_tables: ['nchat_reports'],
    realtime_events: ['report:created'],
    test_file: 'src/app/api/__tests__/moderation-routes.test.ts',
    phase: 13,
    priority: 2,
  },
  {
    id: 'mod-actions',
    name: 'Moderation Actions',
    category: 'moderation',
    description: 'Ban, mute, warn, and other moderation actions',
    status: 'not_started',
    dependencies: ['mod-queue'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['moderation.reportingSystem'],
    ui_component: 'src/components/admin/ReportActions',
    api_endpoint: 'POST /api/moderation/actions',
    db_tables: ['nchat_moderation_actions', 'nchat_bans', 'nchat_mutes', 'nchat_warnings'],
    realtime_events: ['user:banned', 'user:muted', 'user:warned'],
    test_file: 'src/app/api/__tests__/moderation-routes.test.ts',
    phase: 13,
    priority: 2,
  },

  // ===========================================================================
  // BILLING FEATURES (Phase 12)
  // ===========================================================================
  {
    id: 'bill-plans',
    name: 'Subscription Plans',
    category: 'billing',
    description: 'Define and display subscription plans',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['payments.subscriptions'],
    ui_component: 'src/components/billing/PricingTable',
    api_endpoint: 'GET /api/billing/plans',
    db_tables: ['nchat_plans'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/plans.test.ts',
    phase: 12,
    priority: 1,
  },
  {
    id: 'bill-stripe',
    name: 'Stripe Integration',
    category: 'billing',
    description: 'Stripe checkout and subscription management',
    status: 'not_started',
    dependencies: ['bill-plans'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['payments.subscriptions'],
    ui_component: 'src/components/billing/StripeCheckout',
    api_endpoint: 'POST /api/billing/checkout',
    db_tables: ['nchat_subscriptions'],
    realtime_events: ['subscription:created'],
    test_file: 'src/app/api/__tests__/stripe.test.ts',
    phase: 12,
    priority: 1,
  },
  {
    id: 'bill-portal',
    name: 'Customer Portal',
    category: 'billing',
    description: 'Self-service billing management portal',
    status: 'not_started',
    dependencies: ['bill-stripe'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['payments.subscriptions'],
    ui_component: 'src/components/billing/BillingPortal',
    api_endpoint: 'GET /api/billing/portal',
    db_tables: ['nchat_subscriptions'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/portal.test.ts',
    phase: 12,
    priority: 2,
  },
  {
    id: 'bill-crypto',
    name: 'Crypto Payments',
    category: 'billing',
    description: 'Accept cryptocurrency payments',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['payments.crypto'],
    ui_component: 'src/components/billing/CryptoPayment',
    api_endpoint: 'POST /api/billing/crypto',
    db_tables: ['nchat_crypto_payments'],
    realtime_events: ['payment:confirmed'],
    test_file: 'src/app/api/__tests__/crypto.test.ts',
    phase: 12,
    priority: 4,
  },
  {
    id: 'bill-token-gating',
    name: 'Token Gating',
    category: 'billing',
    description: 'Restrict access based on NFT/token ownership',
    status: 'not_started',
    dependencies: ['bill-crypto'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['payments.tokenGating'],
    ui_component: 'src/components/chat/TokenGateSettings',
    api_endpoint: 'POST /api/channels/:id/token-gate',
    db_tables: ['nchat_token_gates'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/token-gate.test.ts',
    phase: 12,
    priority: 5,
  },

  // ===========================================================================
  // VOICE & VIDEO FEATURES (Phase 8)
  // ===========================================================================
  {
    id: 'call-voice-1to1',
    name: '1:1 Voice Calls',
    category: 'voice_video',
    description: 'One-on-one voice calls with WebRTC',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['voice.calls'],
    ui_component: 'src/components/calls/VoiceCallUI',
    api_endpoint: 'POST /api/calls/initiate',
    db_tables: ['nchat_calls'],
    realtime_events: ['call:initiated', 'call:answered', 'call:ended'],
    test_file: 'src/app/api/__tests__/voice-call.test.ts',
    phase: 8,
    priority: 1,
  },
  {
    id: 'call-voice-group',
    name: 'Group Voice Calls',
    category: 'voice_video',
    description: 'Multi-party voice calls',
    status: 'not_started',
    dependencies: ['call-voice-1to1'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['voice.calls'],
    ui_component: 'src/components/calls/GroupCallUI',
    api_endpoint: 'POST /api/calls/initiate',
    db_tables: ['nchat_calls', 'nchat_call_participants'],
    realtime_events: ['call:participant:joined', 'call:participant:left'],
    test_file: 'src/app/api/__tests__/group-call.test.ts',
    phase: 8,
    priority: 2,
  },
  {
    id: 'call-video-1to1',
    name: '1:1 Video Calls',
    category: 'voice_video',
    description: 'One-on-one video calls with WebRTC',
    status: 'not_started',
    dependencies: ['call-voice-1to1'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['video.calls'],
    ui_component: 'src/components/calls/VideoCallUI',
    api_endpoint: 'POST /api/calls/initiate',
    db_tables: ['nchat_calls'],
    realtime_events: ['call:initiated', 'call:answered', 'call:ended'],
    test_file: 'src/app/api/__tests__/video-call.test.ts',
    phase: 8,
    priority: 1,
  },
  {
    id: 'call-video-group',
    name: 'Group Video Calls',
    category: 'voice_video',
    description: 'Multi-party video calls with grid view',
    status: 'not_started',
    dependencies: ['call-video-1to1'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['video.calls'],
    ui_component: 'src/components/calls/GroupVideoUI',
    api_endpoint: 'POST /api/calls/initiate',
    db_tables: ['nchat_calls', 'nchat_call_participants'],
    realtime_events: ['call:participant:joined', 'call:participant:left'],
    test_file: 'src/app/api/__tests__/group-video.test.ts',
    phase: 8,
    priority: 2,
  },
  {
    id: 'call-screen-share',
    name: 'Screen Sharing',
    category: 'voice_video',
    description: 'Share screen during calls',
    status: 'not_started',
    dependencies: ['call-video-1to1'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: ['video.screenShare'],
    ui_component: 'src/components/calls/ScreenShareButton',
    api_endpoint: 'POST /api/calls/:id/screen-share',
    db_tables: ['nchat_calls'],
    realtime_events: ['call:screen:started', 'call:screen:stopped'],
    test_file: 'src/app/api/__tests__/screen-share.test.ts',
    phase: 8,
    priority: 2,
  },
  {
    id: 'call-recording',
    name: 'Call Recording',
    category: 'voice_video',
    description: 'Record calls for later playback',
    status: 'not_started',
    dependencies: ['call-voice-1to1'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['features.callRecording'],
    ui_component: 'src/components/calls/RecordingButton',
    api_endpoint: 'POST /api/calls/:id/record',
    db_tables: ['nchat_call_recordings'],
    realtime_events: ['recording:started', 'recording:stopped'],
    test_file: 'src/app/api/__tests__/recording.test.ts',
    phase: 8,
    priority: 3,
  },
  {
    id: 'call-voice-channels',
    name: 'Voice Channels',
    category: 'voice_video',
    description: 'Persistent voice rooms like Discord',
    status: 'not_started',
    dependencies: ['call-voice-group'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['voice.voiceChannels'],
    ui_component: 'src/components/channels/VoiceChannel',
    api_endpoint: 'POST /api/channels',
    db_tables: ['nchat_channels', 'nchat_voice_states'],
    realtime_events: ['voice:state:updated'],
    test_file: 'src/app/api/__tests__/voice-channel.test.ts',
    phase: 8,
    priority: 3,
  },

  // ===========================================================================
  // STREAMING FEATURES (Phase 8)
  // ===========================================================================
  {
    id: 'stream-start',
    name: 'Live Streaming',
    category: 'streaming',
    description: 'Start live video streams',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['features.liveStreaming'],
    ui_component: 'src/components/streaming/GoLiveButton',
    api_endpoint: 'POST /api/streams',
    db_tables: ['nchat_streams'],
    realtime_events: ['stream:started', 'stream:ended'],
    test_file: 'src/app/api/__tests__/stream.test.ts',
    phase: 8,
    priority: 3,
  },
  {
    id: 'stream-chat',
    name: 'Stream Chat',
    category: 'streaming',
    description: 'Live chat during streams',
    status: 'not_started',
    dependencies: ['stream-start'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['features.streamChat'],
    ui_component: 'src/components/streaming/StreamChat',
    api_endpoint: 'POST /api/streams/:id/messages',
    db_tables: ['nchat_stream_messages'],
    realtime_events: ['stream:message'],
    test_file: 'src/app/api/__tests__/stream-chat.test.ts',
    phase: 8,
    priority: 3,
  },
  {
    id: 'stream-reactions',
    name: 'Stream Reactions',
    category: 'streaming',
    description: 'Live reactions during streams',
    status: 'not_started',
    dependencies: ['stream-start'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['features.streamReactions'],
    ui_component: 'src/components/streaming/StreamReactions',
    api_endpoint: 'POST /api/streams/:id/reactions',
    db_tables: ['nchat_stream_reactions'],
    realtime_events: ['stream:reaction'],
    test_file: 'src/app/api/__tests__/stream-reactions.test.ts',
    phase: 8,
    priority: 4,
  },
  {
    id: 'stream-recording',
    name: 'Stream Recording',
    category: 'streaming',
    description: 'Record live streams for later viewing',
    status: 'not_started',
    dependencies: ['stream-start'],
    backend_enforced: true,
    plan_restrictions: ['business', 'enterprise'],
    flags: ['features.streamRecording'],
    ui_component: 'src/components/streaming/RecordStreamToggle',
    api_endpoint: 'POST /api/streams/:id/record',
    db_tables: ['nchat_stream_recordings'],
    realtime_events: ['recording:started'],
    test_file: 'src/app/api/__tests__/stream-recording.test.ts',
    phase: 8,
    priority: 4,
  },

  // ===========================================================================
  // INTEGRATION FEATURES (Phase 2-3)
  // ===========================================================================
  {
    id: 'int-webhooks',
    name: 'Webhooks',
    category: 'integrations',
    description: 'Incoming and outgoing webhooks',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['integrations.webhooks'],
    ui_component: 'src/components/admin/WebhookSettings',
    api_endpoint: 'POST /api/webhooks',
    db_tables: ['nchat_webhooks'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/webhooks.test.ts',
    phase: 2,
    priority: 2,
  },
  {
    id: 'int-bots',
    name: 'Bot Accounts',
    category: 'integrations',
    description: 'Create and manage bot accounts',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['integrations.bots'],
    ui_component: 'src/components/admin/BotBuilder',
    api_endpoint: 'POST /api/bots',
    db_tables: ['nchat_bots', 'nchat_bot_commands'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/bot-routes.test.ts',
    phase: 2,
    priority: 2,
  },
  {
    id: 'int-github',
    name: 'GitHub Integration',
    category: 'integrations',
    description: 'GitHub notifications and PR linking',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['integrations.github.enabled'],
    ui_component: 'src/components/admin/GitHubSettings',
    api_endpoint: 'POST /api/integrations/github',
    db_tables: ['nchat_github_installations'],
    realtime_events: ['github:event'],
    test_file: 'src/app/api/__tests__/github.test.ts',
    phase: 2,
    priority: 4,
  },
  {
    id: 'int-slack-import',
    name: 'Slack Import',
    category: 'integrations',
    description: 'Import channels and messages from Slack',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['business', 'enterprise'],
    flags: ['integrations.slackImport'],
    ui_component: 'src/components/admin/SlackImportWizard',
    api_endpoint: 'POST /api/integrations/slack/import',
    db_tables: ['nchat_imports'],
    realtime_events: ['import:progress'],
    test_file: 'src/app/api/__tests__/slack-import.test.ts',
    phase: 2,
    priority: 5,
  },
  {
    id: 'int-social',
    name: 'Social Media Integration',
    category: 'integrations',
    description: 'Connect and post to social media accounts',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['integrations.social'],
    ui_component: 'src/components/admin/SocialAccounts',
    api_endpoint: 'GET /api/social/accounts',
    db_tables: ['nchat_social_accounts'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/social.test.ts',
    phase: 2,
    priority: 4,
  },

  // ===========================================================================
  // ADMIN FEATURES (Phase 14)
  // ===========================================================================
  {
    id: 'admin-dashboard',
    name: 'Admin Dashboard',
    category: 'admin',
    description: 'Central admin dashboard with system overview',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['admin.dashboard'],
    ui_component: 'src/components/admin/AdminDashboard',
    api_endpoint: 'GET /api/admin/stats',
    db_tables: [],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/admin.test.ts',
    phase: 14,
    priority: 1,
  },
  {
    id: 'admin-users',
    name: 'User Management',
    category: 'admin',
    description: 'Manage users, roles, and permissions',
    status: 'in_progress',
    dependencies: ['admin-dashboard'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['admin.userManagement'],
    ui_component: 'src/components/admin/UserManagement',
    api_endpoint: 'GET /api/admin/users',
    db_tables: ['nchat_users'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/admin.test.ts',
    phase: 14,
    priority: 1,
  },
  {
    id: 'admin-roles',
    name: 'Role Management',
    category: 'admin',
    description: 'Create and configure custom roles',
    status: 'in_progress',
    dependencies: ['admin-users'],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['admin.roleManagement'],
    ui_component: 'src/components/admin/RoleEditor',
    api_endpoint: 'POST /api/admin/roles',
    db_tables: ['nchat_roles', 'nchat_role_permissions'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/roles.test.ts',
    phase: 14,
    priority: 2,
  },
  {
    id: 'admin-analytics',
    name: 'Analytics Dashboard',
    category: 'admin',
    description: 'View usage analytics and metrics',
    status: 'in_progress',
    dependencies: ['admin-dashboard'],
    backend_enforced: true,
    plan_restrictions: ['pro', 'business', 'enterprise'],
    flags: ['admin.analytics'],
    ui_component: 'src/components/admin/AnalyticsDashboard',
    api_endpoint: 'GET /api/analytics/dashboard',
    db_tables: ['nchat_analytics_messages', 'nchat_analytics_users', 'nchat_analytics_channels'],
    realtime_events: ['analytics:updated'],
    test_file: 'src/app/api/__tests__/analytics.test.ts',
    phase: 14,
    priority: 2,
  },
  {
    id: 'admin-audit',
    name: 'Audit Logs',
    category: 'admin',
    description: 'View and export audit logs',
    status: 'in_progress',
    dependencies: ['admin-dashboard'],
    backend_enforced: true,
    plan_restrictions: ['business', 'enterprise'],
    flags: ['admin.auditLog'],
    ui_component: 'src/components/admin/AuditLogViewer',
    api_endpoint: 'GET /api/audit',
    db_tables: ['nchat_audit_logs'],
    realtime_events: [],
    test_file: 'src/graphql/__tests__/audit.test.ts',
    phase: 14,
    priority: 2,
  },

  // ===========================================================================
  // COMPLIANCE FEATURES (Phase 13)
  // ===========================================================================
  {
    id: 'comp-data-export',
    name: 'GDPR Data Export',
    category: 'compliance',
    description: 'Export all user data for GDPR compliance',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['compliance.gdpr'],
    ui_component: 'src/components/settings/DataExportRequest',
    api_endpoint: 'POST /api/compliance/export',
    db_tables: ['nchat_export_requests'],
    realtime_events: ['export:ready'],
    test_file: 'src/app/api/__tests__/export.test.ts',
    phase: 13,
    priority: 2,
  },
  {
    id: 'comp-account-deletion',
    name: 'Account Deletion',
    category: 'compliance',
    description: 'Delete account and all associated data',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['compliance.gdpr'],
    ui_component: 'src/components/settings/DeleteAccountFlow',
    api_endpoint: 'POST /api/compliance/deletion',
    db_tables: ['nchat_deletion_requests'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/deletion.test.ts',
    phase: 13,
    priority: 2,
  },
  {
    id: 'comp-consent',
    name: 'Consent Management',
    category: 'compliance',
    description: 'Track and manage user consent',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: [],
    flags: ['compliance.gdpr'],
    ui_component: 'src/components/compliance/ConsentBanner',
    api_endpoint: 'POST /api/compliance/consent',
    db_tables: ['nchat_consents'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/consent.test.ts',
    phase: 13,
    priority: 3,
  },
  {
    id: 'comp-legal-hold',
    name: 'Legal Hold',
    category: 'compliance',
    description: 'Place legal holds on user data',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['enterprise'],
    flags: ['compliance.legalHold'],
    ui_component: 'src/components/admin/LegalHoldManager',
    api_endpoint: 'POST /api/compliance/legal-hold',
    db_tables: ['nchat_legal_holds'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/legal-hold.test.ts',
    phase: 13,
    priority: 4,
  },
  {
    id: 'comp-retention',
    name: 'Data Retention Policies',
    category: 'compliance',
    description: 'Configure automatic data retention and deletion',
    status: 'not_started',
    dependencies: [],
    backend_enforced: true,
    plan_restrictions: ['business', 'enterprise'],
    flags: ['compliance.retention'],
    ui_component: 'src/components/admin/RetentionPolicy',
    api_endpoint: 'PATCH /api/admin/retention',
    db_tables: ['nchat_retention_policies'],
    realtime_events: [],
    test_file: 'src/app/api/__tests__/retention.test.ts',
    phase: 13,
    priority: 3,
  },

  // ===========================================================================
  // PLATFORM FEATURES (Phase 16)
  // ===========================================================================
  {
    id: 'plat-web',
    name: 'Web Application',
    category: 'platform',
    description: 'Browser-based web application',
    status: 'in_progress',
    dependencies: [],
    backend_enforced: false,
    plan_restrictions: [],
    flags: [],
    ui_component: 'src/app',
    api_endpoint: undefined,
    db_tables: [],
    realtime_events: [],
    test_file: 'e2e/web',
    platforms: ['web'],
    phase: 16,
    priority: 1,
  },
  {
    id: 'plat-ios',
    name: 'iOS Application',
    category: 'platform',
    description: 'Native iOS application via Capacitor',
    status: 'not_started',
    dependencies: ['plat-web'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: [],
    ui_component: 'platforms/capacitor',
    api_endpoint: undefined,
    db_tables: [],
    realtime_events: [],
    test_file: 'e2e/ios',
    platforms: ['ios'],
    phase: 16,
    priority: 2,
  },
  {
    id: 'plat-android',
    name: 'Android Application',
    category: 'platform',
    description: 'Native Android application via Capacitor',
    status: 'not_started',
    dependencies: ['plat-web'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: [],
    ui_component: 'platforms/capacitor',
    api_endpoint: undefined,
    db_tables: [],
    realtime_events: [],
    test_file: 'e2e/android',
    platforms: ['android'],
    phase: 16,
    priority: 2,
  },
  {
    id: 'plat-desktop',
    name: 'Desktop Application',
    category: 'platform',
    description: 'Native desktop application via Tauri/Electron',
    status: 'not_started',
    dependencies: ['plat-web'],
    backend_enforced: false,
    plan_restrictions: [],
    flags: [],
    ui_component: 'platforms/tauri',
    api_endpoint: undefined,
    db_tables: [],
    realtime_events: [],
    test_file: 'e2e/desktop',
    platforms: ['macos', 'windows', 'linux'],
    phase: 16,
    priority: 3,
  },
] as const

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get all features in a specific category
 */
export function getFeaturesByCategory(category: FeatureCategory): Feature[] {
  return FEATURE_REGISTRY.filter((f) => f.category === category) as Feature[]
}

/**
 * Get all features with a specific status
 */
export function getFeaturesByStatus(status: FeatureStatus): Feature[] {
  return FEATURE_REGISTRY.filter((f) => f.status === status) as Feature[]
}

/**
 * Get a feature by its ID
 */
export function getFeatureById(id: string): Feature | undefined {
  return FEATURE_REGISTRY.find((f) => f.id === id) as Feature | undefined
}

/**
 * Get all features for a specific phase
 */
export function getFeaturesByPhase(phase: number): Feature[] {
  return FEATURE_REGISTRY.filter((f) => f.phase === phase) as Feature[]
}

/**
 * Get all features restricted to specific plans
 */
export function getFeaturesByPlan(plan: PlanLevel): Feature[] {
  return FEATURE_REGISTRY.filter(
    (f) => f.plan_restrictions.length === 0 || f.plan_restrictions.includes(plan)
  ) as Feature[]
}

/**
 * Get all feature IDs that are dependencies of a given feature
 */
export function getFeatureDependencies(featureId: string): string[] {
  const feature = getFeatureById(featureId)
  if (!feature) return []

  const allDeps: string[] = [...feature.dependencies]
  for (const depId of feature.dependencies) {
    allDeps.push(...getFeatureDependencies(depId))
  }
  return [...new Set(allDeps)]
}

/**
 * Get all features that depend on a given feature
 */
export function getFeatureDependents(featureId: string): Feature[] {
  return FEATURE_REGISTRY.filter((f) => f.dependencies.includes(featureId)) as Feature[]
}

/**
 * Check if a feature is available for a given plan
 */
export function isFeatureAvailableForPlan(featureId: string, plan: PlanLevel): boolean {
  const feature = getFeatureById(featureId)
  if (!feature) return false
  if (feature.plan_restrictions.length === 0) return true
  return feature.plan_restrictions.includes(plan)
}

/**
 * Get summary statistics for the feature registry
 */
export function getFeatureStats(): {
  total: number
  by_status: Record<FeatureStatus, number>
  by_category: Record<FeatureCategory, number>
  completion_percentage: number
} {
  const stats = {
    total: FEATURE_REGISTRY.length,
    by_status: {
      not_started: 0,
      in_progress: 0,
      complete: 0,
      blocked: 0,
    } as Record<FeatureStatus, number>,
    by_category: {} as Record<FeatureCategory, number>,
    completion_percentage: 0,
  }

  for (const feature of FEATURE_REGISTRY) {
    stats.by_status[feature.status]++
    stats.by_category[feature.category] = (stats.by_category[feature.category] || 0) + 1
  }

  stats.completion_percentage = Math.round((stats.by_status.complete / stats.total) * 100)

  return stats
}

/**
 * Get all unique database tables referenced by features
 */
export function getAllDatabaseTables(): string[] {
  const tables = new Set<string>()
  for (const feature of FEATURE_REGISTRY) {
    for (const table of feature.db_tables || []) {
      tables.add(table)
    }
  }
  return Array.from(tables).sort()
}

/**
 * Get all unique realtime events referenced by features
 */
export function getAllRealtimeEvents(): string[] {
  const events = new Set<string>()
  for (const feature of FEATURE_REGISTRY) {
    for (const event of feature.realtime_events || []) {
      events.add(event)
    }
  }
  return Array.from(events).sort()
}

/**
 * Get all unique feature flags referenced by features
 */
export function getAllFeatureFlags(): string[] {
  const flags = new Set<string>()
  for (const feature of FEATURE_REGISTRY) {
    for (const flag of feature.flags) {
      flags.add(flag)
    }
  }
  return Array.from(flags).sort()
}

// =============================================================================
// CATEGORY METADATA
// =============================================================================

export const CATEGORY_METADATA: Record<
  FeatureCategory,
  { name: string; description: string; icon: string }
> = {
  messaging: {
    name: 'Messaging',
    description: 'Core messaging features including text, reactions, threads, and scheduling',
    icon: 'MessageSquare',
  },
  channels: {
    name: 'Channels & Communities',
    description: 'Channel types, organization, and community structures',
    icon: 'Hash',
  },
  presence: {
    name: 'Presence & Status',
    description: 'Online status, typing indicators, and read receipts',
    icon: 'Circle',
  },
  media: {
    name: 'Media',
    description: 'Image, video, file uploads, and media management',
    icon: 'Image',
  },
  search: {
    name: 'Search',
    description: 'Full-text and AI-powered search capabilities',
    icon: 'Search',
  },
  notifications: {
    name: 'Notifications',
    description: 'Push, email, and in-app notifications',
    icon: 'Bell',
  },
  authentication: {
    name: 'Authentication',
    description: 'Login methods, OAuth, SSO, and session management',
    icon: 'Key',
  },
  e2ee: {
    name: 'End-to-End Encryption',
    description: 'Signal-grade encryption and device security',
    icon: 'Lock',
  },
  moderation: {
    name: 'Moderation',
    description: 'Content moderation, reporting, and automated actions',
    icon: 'Shield',
  },
  billing: {
    name: 'Billing & Monetization',
    description: 'Subscriptions, payments, and access control',
    icon: 'CreditCard',
  },
  voice_video: {
    name: 'Voice & Video',
    description: 'Voice calls, video calls, and screen sharing',
    icon: 'Video',
  },
  streaming: {
    name: 'Live Streaming',
    description: 'Live video streaming with chat and reactions',
    icon: 'Radio',
  },
  integrations: {
    name: 'Integrations',
    description: 'Webhooks, bots, and third-party integrations',
    icon: 'Plug',
  },
  admin: {
    name: 'Admin & Analytics',
    description: 'Administration dashboard and analytics',
    icon: 'Settings',
  },
  compliance: {
    name: 'Compliance',
    description: 'GDPR, data retention, and legal compliance',
    icon: 'FileCheck',
  },
  platform: {
    name: 'Platform Support',
    description: 'Multi-platform builds and native features',
    icon: 'Smartphone',
  },
}

// =============================================================================
// TYPE EXPORTS
// =============================================================================

// Types are already exported at the top of the file
