/**
 * Utility library for nself-chat
 * Re-exports all utility modules for convenient imports
 * @module utils
 */

// Format utilities
export {
  formatDate,
  formatTime,
  formatFileSize,
  formatDuration,
  formatNumber,
  formatUserName,
  formatMessageTime,
  formatPercentage,
  type DateFormatOptions,
} from "./format";

// Validation utilities
export {
  validateEmail,
  validatePassword,
  validateChannelName,
  validateUsername,
  validateMessageLength,
  validateFileType,
  validateFileSize,
  validateUrl,
  validateDisplayName,
  combineValidations,
  calculatePasswordStrength,
  type ValidationResult,
  type PasswordStrength,
  type PasswordOptions,
  type FileTypeConfig,
} from "./validation";

// String utilities
export {
  truncate,
  slugify,
  highlight,
  escapeHtml,
  unescapeHtml,
  parseMarkdown,
  extractMentions,
  extractChannels,
  extractUrls,
  linkifyUrls,
  capitalize,
  titleCase,
  camelCase,
  kebabCase,
  snakeCase,
  wordCount,
  stripHtml,
  normalizeWhitespace,
  pad,
  contains,
  removeDiacritics,
  initials,
  reverse,
  isValidJson,
  byteSize,
  type TruncateOptions,
  type SlugifyOptions,
} from "./string";

// Array utilities
export {
  groupBy,
  sortBy,
  uniqueBy,
  chunk,
  move,
  insertAt,
  removeAt,
  removeWhere,
  updateAt,
  updateWhere,
  flatten,
  first,
  last,
  intersection,
  difference,
  union,
  shuffle,
  sample,
  sampleN,
  partition,
  count,
  range,
  zip,
  findIndex,
  every,
  some,
  toLookup,
  type SortDirection,
  type SortConfig,
} from "./array";

// Object utilities
export {
  deepMerge,
  pick,
  omit,
  deepClone,
  isEqual,
  isEmpty,
  get,
  set,
  unset,
  has,
  flattenObject,
  unflattenObject,
  mapValues,
  mapKeys,
  filterObject,
  compact,
  fromEntries,
  invert,
  mergeWith,
  diff,
  isPlainObject,
  type AnyObject,
} from "./object";

// DOM utilities
export {
  copyToClipboard,
  readFromClipboard,
  downloadFile,
  downloadFromUrl,
  scrollToElement,
  scrollToTop,
  scrollToBottom,
  isElementInView,
  getScrollParent,
  getScrollPosition,
  getElementDimensions,
  focusElement,
  dispatchCustomEvent,
  addEventListenerWithCleanup,
  waitForElement,
  lockScroll,
  getActiveElement,
  containsElement,
  isBrowser,
  type DownloadOptions,
  type ScrollBehavior,
  type ScrollAlignment,
  type ScrollToElementOptions,
} from "./dom";

// Storage utilities
export {
  createLocalStorage,
  createSessionStorage,
  createIndexedDB,
  getStorageQuota,
  requestPersistentStorage,
  isStoragePersisted,
  createMemoryCache,
  type StorageOptions,
  type IDBConfig,
  type StorageQuota,
} from "./storage";

// Timing utilities (debounce)
export {
  debounce,
  throttle,
  delay,
  cancellableDelay,
  retry,
  once,
  after,
  before,
  createInterval,
  createTimeout,
  createRateLimiter,
  sequence,
  timeout,
  type DebounceOptions,
  type DebouncedFunction,
  type ThrottleOptions,
  type ThrottledFunction,
  type RetryOptions,
  type RateLimiterOptions,
} from "./debounce";

// URL utilities
export {
  parseUrl,
  buildUrl,
  getQueryParams,
  getQueryParam,
  setQueryParams,
  removeQueryParams,
  isExternalUrl,
  isAbsoluteUrl,
  isValidUrl,
  getUrlDomain,
  getUrlExtension,
  joinPath,
  normalizePath,
  encodeUrlComponent,
  decodeUrlComponent,
  toUrlSlug,
  setUrlHash,
  getUrlHash,
  isSameUrl,
  addUtmParams,
  matchUrlPattern,
  type ParsedUrl,
  type BuildUrlOptions,
} from "./url";

// Color utilities
export {
  hexToRgb,
  hexToRgba,
  rgbToHex,
  rgbaToHex,
  rgbToHsl,
  hslToRgb,
  hexToHsl,
  hslToHex,
  lighten,
  darken,
  saturate,
  desaturate,
  adjustHue,
  getComplementary,
  getContrastColor,
  getLuminance,
  getContrastRatio,
  meetsContrastRequirement,
  mix,
  tint,
  shade,
  generatePalette,
  getTriadic,
  getAnalogous,
  getSplitComplementary,
  toGrayscale,
  invert as invertColor,
  isValidHex,
  parseColor,
  toRgbString,
  toHslString,
  type RGB,
  type RGBA,
  type HSL,
  type HSLA,
} from "./color";

// Keyboard utilities
export {
  isModifierKey,
  getKeyCombo,
  parseShortcut,
  matchesShortcut,
  preventDefaultHandler,
  formatShortcut,
  isPrintableKey,
  isInputEvent,
  createShortcutHandler,
  getFocusableElements,
  createFocusTrap,
  getPlatformModifier,
  isMacPlatform,
  KEY_CODES,
  type ModifierKey,
  type KeyboardShortcut,
} from "./keyboard";

// Media utilities
export {
  getImageDimensions,
  getVideoMetadata,
  getVideoDuration,
  getAudioMetadata,
  createThumbnail,
  createVideoThumbnail,
  compressImage,
  canvasToBlob,
  blobToDataUrl,
  dataUrlToBlob,
  isImageFile,
  isVideoFile,
  isAudioFile,
  getMediaType,
  isMediaTypeSupported,
  preloadImage,
  preloadImages,
  calculateDisplayDimensions,
  rotateImage,
  flipImage,
  type ImageDimensions,
  type VideoMetadata,
  type AudioMetadata,
  type ThumbnailOptions,
  type CompressionOptions,
} from "./media";

// Crypto utilities
export {
  generateId,
  generateUUID,
  generateShortId,
  generateNumericId,
  randomString,
  hashString,
  simpleHash,
  generateHMAC,
  verifyHMAC,
  constantTimeCompare,
  base64Encode,
  base64Decode,
  base64UrlEncode,
  base64UrlDecode,
  bufferToHex,
  hexToBuffer,
  randomBytes,
  generateSecureToken,
  hashPassword,
  createFingerprint,
  generateSlugId,
  isCryptoAvailable,
  isSubtleCryptoAvailable,
  type HashAlgorithm,
} from "./crypto";
